
package com.velotech.fanselection.models;
// Generated May 29, 2019 3:23:32 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl28SelectedPricing generated by hbm2java
 */
@Entity
@Table(name = "tbl_28_selected_pricing")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl28SelectedPricing implements java.io.Serializable {

	private int id;

	private Tbl26OfferFan tbl26OfferFan;

	private Tbl01ProductMaster tbl01ProductMaster;

	private Integer sorting;

	private String itemName;

	private String description;

	private Integer qty;

	private String source;

	private Double discount;

	private String articleNo;

	private Double pricePerQty;

	private Double subTotal;

	private String scope;

	private String groupClass;

	private String recordType;

	private String make;

	private Double margin;

	private Boolean applyFactor;

	private Double totalOfferFactor;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl28SelectedPricing() {
	}

	public Tbl28SelectedPricing(int id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "offerFan_id")
	public Tbl26OfferFan getTbl26OfferFan() {

		return this.tbl26OfferFan;
	}

	public void setTbl26OfferFan(Tbl26OfferFan tbl26OfferFan) {

		this.tbl26OfferFan = tbl26OfferFan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productMasterId")
	public Tbl01ProductMaster getTbl01ProductMaster() {

		return this.tbl01ProductMaster;
	}

	public void setTbl01ProductMaster(Tbl01ProductMaster tbl01ProductMaster) {

		this.tbl01ProductMaster = tbl01ProductMaster;
	}

	@Column(name = "sorting")
	public Integer getSorting() {

		return this.sorting;
	}

	public void setSorting(Integer sorting) {

		this.sorting = sorting;
	}

	@Column(name = "itemName", length = 50)
	public String getItemName() {

		return this.itemName;
	}

	public void setItemName(String itemName) {

		this.itemName = itemName;
	}

	@Column(name = "description")
	public String getDescription() {

		return this.description;
	}

	public void setDescription(String description) {

		this.description = description;
	}

	@Column(name = "qty")
	public Integer getQty() {

		return this.qty;
	}

	public void setQty(Integer qty) {

		this.qty = qty;
	}

	@Column(name = "source", length = 50)
	public String getSource() {

		return this.source;
	}

	public void setSource(String source) {

		this.source = source;
	}

	@Column(name = "discount", precision = 6, scale = 3)
	public Double getDiscount() {

		return this.discount;
	}

	public void setDiscount(Double discount) {

		this.discount = discount;
	}

	@Column(name = "articleNo", length = 50)
	public String getArticleNo() {

		return this.articleNo;
	}

	public void setArticleNo(String articleNo) {

		this.articleNo = articleNo;
	}

	@Column(name = "pricePerQty", precision = 18)
	public Double getPricePerQty() {

		return this.pricePerQty;
	}

	public void setPricePerQty(Double pricePerQty) {

		this.pricePerQty = pricePerQty;
	}

	@Column(name = "subTotal", precision = 18)
	public Double getSubTotal() {

		return this.subTotal;
	}

	public void setSubTotal(Double subTotal) {

		this.subTotal = subTotal;
	}

	@Column(name = "scope", length = 50)
	public String getScope() {

		return this.scope;
	}

	public void setScope(String scope) {

		this.scope = scope;
	}

	@Column(name = "groupClass", length = 50)
	public String getGroupClass() {

		return this.groupClass;
	}

	public void setGroupClass(String groupClass) {

		this.groupClass = groupClass;
	}

	@Column(name = "recordType", length = 50)
	public String getRecordType() {

		return this.recordType;
	}

	public void setRecordType(String recordType) {

		this.recordType = recordType;
	}

	@Column(name = "make", length = 50)
	public String getMake() {

		return this.make;
	}

	public void setMake(String make) {

		this.make = make;
	}

	@Column(name = "margin", precision = 6, scale = 3)
	public Double getMargin() {

		return this.margin;
	}

	public void setMargin(Double margin) {

		this.margin = margin;
	}

	@Column(name = "applyFactor")
	public Boolean getApplyFactor() {

		return this.applyFactor;
	}

	public void setApplyFactor(Boolean applyFactor) {

		this.applyFactor = applyFactor;
	}

	@Column(name = "totalOfferFactor", precision = 18)
	public Double getTotalOfferFactor() {

		return this.totalOfferFactor;
	}

	public void setTotalOfferFactor(Double totalOfferFactor) {

		this.totalOfferFactor = totalOfferFactor;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}
}
