
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl03MaterialMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_03_materialMaster", uniqueConstraints = @UniqueConstraint(columnNames = {
		"specification", "company" }))
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl03MaterialMaster implements java.io.Serializable {

	private int materialId;

	private String specification;

	private String genericName;

	private String nameIs;

	private String nameBs;

	private String nameAstm;

	private String nameDin;

	private String nameJis;

	private String nameEn;

	private String remarks;

	private Double maxPermissibleTipSpeed;

	private Double allowableStress;

	private Double shearStress;

	private Double tensileStrength;

	private Double hardness;

	private Double density;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl03MaterialMaster() {
	}

	public Tbl03MaterialMaster(int materialId) {
		this.materialId = materialId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "material_id", unique = true, nullable = false)
	public int getMaterialId() {

		return this.materialId;
	}

	public void setMaterialId(int materialId) {

		this.materialId = materialId;
	}

	@Column(name = "specification")
	public String getSpecification() {

		return this.specification;
	}

	public void setSpecification(String specification) {

		this.specification = specification;
	}

	@Column(name = "genericName")
	public String getGenericName() {

		return this.genericName;
	}

	public void setGenericName(String genericName) {

		this.genericName = genericName;
	}

	@Column(name = "name_IS")
	public String getNameIs() {

		return this.nameIs;
	}

	public void setNameIs(String nameIs) {

		this.nameIs = nameIs;
	}

	@Column(name = "name_BS")
	public String getNameBs() {

		return this.nameBs;
	}

	public void setNameBs(String nameBs) {

		this.nameBs = nameBs;
	}

	@Column(name = "name_ASTM")
	public String getNameAstm() {

		return this.nameAstm;
	}

	public void setNameAstm(String nameAstm) {

		this.nameAstm = nameAstm;
	}

	@Column(name = "name_DIN")
	public String getNameDin() {

		return this.nameDin;
	}

	public void setNameDin(String nameDin) {

		this.nameDin = nameDin;
	}

	@Column(name = "name_JIS")
	public String getNameJis() {

		return this.nameJis;
	}

	public void setNameJis(String nameJis) {

		this.nameJis = nameJis;
	}

	@Column(name = "name_EN")
	public String getNameEn() {

		return this.nameEn;
	}

	public void setNameEn(String nameEn) {

		this.nameEn = nameEn;
	}

	@Column(name = "remarks")
	public String getRemarks() {

		return this.remarks;
	}

	public void setRemarks(String remarks) {

		this.remarks = remarks;
	}

	@Column(name = "maxPermissibleTipSpeed", precision = 18, scale = 4)
	public Double getMaxPermissibleTipSpeed() {

		return this.maxPermissibleTipSpeed;
	}

	public void setMaxPermissibleTipSpeed(Double maxPermissibleTipSpeed) {

		this.maxPermissibleTipSpeed = maxPermissibleTipSpeed;
	}

	@Column(name = "allowableStress", precision = 18, scale = 4)
	public Double getAllowableStress() {

		return this.allowableStress;
	}

	public void setAllowableStress(Double allowableStress) {

		this.allowableStress = allowableStress;
	}

	@Column(name = "shearStress", precision = 18, scale = 4)
	public Double getShearStress() {

		return this.shearStress;
	}

	public void setShearStress(Double shearStress) {

		this.shearStress = shearStress;
	}

	@Column(name = "tensileStrength", precision = 18, scale = 4)
	public Double getTensileStrength() {

		return this.tensileStrength;
	}

	public void setTensileStrength(Double tensileStrength) {

		this.tensileStrength = tensileStrength;
	}

	@Column(name = "hardness", precision = 18, scale = 4)
	public Double getHardness() {

		return this.hardness;
	}

	public void setHardness(Double hardness) {

		this.hardness = hardness;
	}

	@Column(name = "density", precision = 18, scale = 4)
	public Double getDensity() {

		return this.density;
	}

	public void setDensity(Double density) {

		this.density = density;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

}
