
package com.velotech.fanselection.models.views;
// Generated Aug 6, 2019 4:13:18 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * MisOffer generated by hbm2java
 */
@Entity
@Table(name = "misOffer")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class MisOffer implements java.io.Serializable {

	private MisOfferId id;

	public MisOffer() {
	}

	public MisOffer(MisOfferId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "offerMasterId", column = @Column(name = "offerMasterId", nullable = false)),
			@AttributeOverride(name = "offerNo", column = @Column(name = "offerNo", length = 50)),
			@AttributeOverride(name = "offerRevId", column = @Column(name = "offerRevId", nullable = false)),
			@AttributeOverride(name = "offerRev", column = @Column(name = "offerRev", nullable = false, length = 5)),
			@AttributeOverride(name = "isOrder", column = @Column(name = "isOrder")),
			@AttributeOverride(name = "orderPrice", column = @Column(name = "orderPrice", precision = 18)),
			@AttributeOverride(name = "segmentId", column = @Column(name = "segmentId")),
			@AttributeOverride(name = "segment", column = @Column(name = "segment", nullable = false)),
			@AttributeOverride(name = "offerDate", column = @Column(name = "offerDate", length = 10)),
			@AttributeOverride(name = "customerId", column = @Column(name = "customerId")),
			@AttributeOverride(name = "customerName", column = @Column(name = "customerName")),
			@AttributeOverride(name = "offerStatus", column = @Column(name = "offerStatus")),
			@AttributeOverride(name = "project", column = @Column(name = "project")),
			@AttributeOverride(name = "consultant", column = @Column(name = "consultant")),
			@AttributeOverride(name = "endUser", column = @Column(name = "endUser")),
			@AttributeOverride(name = "contractor", column = @Column(name = "contractor")),
			@AttributeOverride(name = "currency", column = @Column(name = "currency", length = 10)),
			@AttributeOverride(name = "loginId", column = @Column(name = "loginId", length = 100)),
			@AttributeOverride(name = "activeFlag", column = @Column(name = "activeFlag")),
			@AttributeOverride(name = "standardOffer", column = @Column(name = "standardOffer")),
			@AttributeOverride(name = "offerTotal", column = @Column(name = "offerTotal", precision = 18)),
			@AttributeOverride(name = "salesPerson", column = @Column(name = "salesPerson", length = 100)),
			@AttributeOverride(name = "company", column = @Column(name = "company", length = 50)) })
	public MisOfferId getId() {

		return this.id;
	}

	public void setId(MisOfferId id) {

		this.id = id;
	}

}
