
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl90SearchHistory generated by hbm2java
 */
@Entity
@Table(name = "tbl_90_search_history")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl90SearchHistory implements java.io.Serializable {

	private int id;

	private String flow;

	private String head;

	private Double flowConverted;

	private Double headConverted;

	private String headVertical;

	private String uomFlow;

	private String uomHead;

	private String system;

	private Integer qty;

	private Integer totalQty;

	private String frequency;

	private String npsha;

	private String orientation;

	private String suctionPressure;

	private String uomPressure;

	private String primemoverType;

	private String searchCriteria;

	private String speed;

	private String driverSizing;

	private String driverSizingPerofdp;

	private String serviceFactor;

	private String mounting;

	private String effClass;

	private String specification;

	private String ambientTemp;

	private String tempClass;

	private Integer pole;

	private String manufacturer;

	private String liquidType;

	private String fluidName;

	private String liquidDescription;

	private String maxSolidDia;

	private String uomSolidSize;

	private String maxSolidDiaConverted;

	private String solidConcentration;

	private String temperature;

	private String uomTemperature;

	private String spgr;

	private String viscosity;

	private String uomViscosity;

	private String vaporPressure;

	private Boolean effModifierImpellerType;

	private Boolean effModifierMoc;

	private Boolean effModifierStages;

	private Boolean effModifierCoating;

	private String addEff;

	private String testingStandard;

	private String seal;

	private String lubrication;

	private String application;

	private String minSoh;

	private String maxSoh;

	private String maxFlow;

	private String minHead;

	private String sumpDepth;

	private String dbmstype;

	private String fluidLevel;

	private String approach;

	private String series;

	private String pumpModel;

	private String perfCurvNo;

	private String trimDia;

	private String maxDia;

	private String minDia;

	private String diaList;

	private String trimRatio;

	private String mocId;

	private String rotation;

	private String wearRing;

	private String feetLocation;

	private String suctionOrientation;

	private String dischargeOrientation;

	private String flangeType;

	private String companionFlange;

	private String customer;

	private String consultant;

	private String endUser;

	private String project;

	private String contractor;

	private String suppliedBy;

	private Date offerDate;

	private String tagNo;

	private String offerNo;

	private String offerRev;

	private Boolean quickDoc;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl90SearchHistory() {
	}

	public Tbl90SearchHistory(int id) {
		this.id = id;
	}

	public Tbl90SearchHistory(int id, String flow, String head, Double flowConverted, Double headConverted, String headVertical, String uomFlow,
			String uomHead, String system, Integer qty, Integer totalQty, String frequency, String npsha, String orientation, String suctionPressure,
			String uomPressure, String primemoverType, String searchCriteria, String speed, String driverSizing, String driverSizingPerofdp,
			String serviceFactor, String mounting, String effClass, String specification, String ambientTemp, String tempClass, Integer pole,
			String manufacturer, String liquidType, String fluidName, String liquidDescription, String maxSolidDia, String uomSolidSize,
			String maxSolidDiaConverted, String solidConcentration, String temperature, String uomTemperature, String spgr, String viscosity,
			String uomViscosity, String vaporPressure, Boolean effModifierImpellerType, Boolean effModifierMoc, Boolean effModifierStages,
			Boolean effModifierCoating, String addEff, String testingStandard, String seal, String lubrication, String application, String minSoh,
			String maxSoh, String maxFlow, String minHead, String sumpDepth, String dbmstype, String fluidLevel, String approach, String series,
			String pumpModel, String perfCurvNo, String trimDia, String maxDia, String minDia, String diaList, String trimRatio, String mocId,
			String rotation, String wearRing, String feetLocation, String suctionOrientation, String dischargeOrientation, String flangeType,
			String companionFlange, String customer, String consultant, String endUser, String project, String contractor, String suppliedBy,
			Date offerDate, String tagNo, String offerNo, String offerRev, Boolean quickDoc, String createdBy, Date createdDate, String modifiedBy,
			Date modifiedDate, String company) {
		this.id = id;
		this.flow = flow;
		this.head = head;
		this.flowConverted = flowConverted;
		this.headConverted = headConverted;
		this.headVertical = headVertical;
		this.uomFlow = uomFlow;
		this.uomHead = uomHead;
		this.system = system;
		this.qty = qty;
		this.totalQty = totalQty;
		this.frequency = frequency;
		this.npsha = npsha;
		this.orientation = orientation;
		this.suctionPressure = suctionPressure;
		this.uomPressure = uomPressure;
		this.primemoverType = primemoverType;
		this.searchCriteria = searchCriteria;
		this.speed = speed;
		this.driverSizing = driverSizing;
		this.driverSizingPerofdp = driverSizingPerofdp;
		this.serviceFactor = serviceFactor;
		this.mounting = mounting;
		this.effClass = effClass;
		this.specification = specification;
		this.ambientTemp = ambientTemp;
		this.tempClass = tempClass;
		this.pole = pole;
		this.manufacturer = manufacturer;
		this.liquidType = liquidType;
		this.fluidName = fluidName;
		this.liquidDescription = liquidDescription;
		this.maxSolidDia = maxSolidDia;
		this.uomSolidSize = uomSolidSize;
		this.maxSolidDiaConverted = maxSolidDiaConverted;
		this.solidConcentration = solidConcentration;
		this.temperature = temperature;
		this.uomTemperature = uomTemperature;
		this.spgr = spgr;
		this.viscosity = viscosity;
		this.uomViscosity = uomViscosity;
		this.vaporPressure = vaporPressure;
		this.effModifierImpellerType = effModifierImpellerType;
		this.effModifierMoc = effModifierMoc;
		this.effModifierStages = effModifierStages;
		this.effModifierCoating = effModifierCoating;
		this.addEff = addEff;
		this.testingStandard = testingStandard;
		this.seal = seal;
		this.lubrication = lubrication;
		this.application = application;
		this.minSoh = minSoh;
		this.maxSoh = maxSoh;
		this.maxFlow = maxFlow;
		this.minHead = minHead;
		this.sumpDepth = sumpDepth;
		this.dbmstype = dbmstype;
		this.fluidLevel = fluidLevel;
		this.approach = approach;
		this.series = series;
		this.pumpModel = pumpModel;
		this.perfCurvNo = perfCurvNo;
		this.trimDia = trimDia;
		this.maxDia = maxDia;
		this.minDia = minDia;
		this.diaList = diaList;
		this.trimRatio = trimRatio;
		this.mocId = mocId;
		this.rotation = rotation;
		this.wearRing = wearRing;
		this.feetLocation = feetLocation;
		this.suctionOrientation = suctionOrientation;
		this.dischargeOrientation = dischargeOrientation;
		this.flangeType = flangeType;
		this.companionFlange = companionFlange;
		this.customer = customer;
		this.consultant = consultant;
		this.endUser = endUser;
		this.project = project;
		this.contractor = contractor;
		this.suppliedBy = suppliedBy;
		this.offerDate = offerDate;
		this.tagNo = tagNo;
		this.offerNo = offerNo;
		this.offerRev = offerRev;
		this.quickDoc = quickDoc;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.company = company;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@Column(name = "flow", length = 50)
	public String getFlow() {

		return this.flow;
	}

	public void setFlow(String flow) {

		this.flow = flow;
	}

	@Column(name = "head", length = 50)
	public String getHead() {

		return this.head;
	}

	public void setHead(String head) {

		this.head = head;
	}

	@Column(name = "flowConverted", precision = 18)
	public Double getFlowConverted() {

		return this.flowConverted;
	}

	public void setFlowConverted(Double flowConverted) {

		this.flowConverted = flowConverted;
	}

	@Column(name = "headConverted", precision = 18)
	public Double getHeadConverted() {

		return this.headConverted;
	}

	public void setHeadConverted(Double headConverted) {

		this.headConverted = headConverted;
	}

	@Column(name = "headVertical", length = 50)
	public String getHeadVertical() {

		return this.headVertical;
	}

	public void setHeadVertical(String headVertical) {

		this.headVertical = headVertical;
	}

	@Column(name = "uomFlow", length = 50)
	public String getUomFlow() {

		return this.uomFlow;
	}

	public void setUomFlow(String uomFlow) {

		this.uomFlow = uomFlow;
	}

	@Column(name = "uomHead", length = 50)
	public String getUomHead() {

		return this.uomHead;
	}

	public void setUomHead(String uomHead) {

		this.uomHead = uomHead;
	}

	@Column(name = "system", length = 50)
	public String getSystem() {

		return this.system;
	}

	public void setSystem(String system) {

		this.system = system;
	}

	@Column(name = "qty")
	public Integer getQty() {

		return this.qty;
	}

	public void setQty(Integer qty) {

		this.qty = qty;
	}

	@Column(name = "totalQty")
	public Integer getTotalQty() {

		return this.totalQty;
	}

	public void setTotalQty(Integer totalQty) {

		this.totalQty = totalQty;
	}

	@Column(name = "frequency", length = 50)
	public String getFrequency() {

		return this.frequency;
	}

	public void setFrequency(String frequency) {

		this.frequency = frequency;
	}

	@Column(name = "npsha", length = 50)
	public String getNpsha() {

		return this.npsha;
	}

	public void setNpsha(String npsha) {

		this.npsha = npsha;
	}

	@Column(name = "orientation", length = 50)
	public String getOrientation() {

		return this.orientation;
	}

	public void setOrientation(String orientation) {

		this.orientation = orientation;
	}

	@Column(name = "suction_pressure", length = 50)
	public String getSuctionPressure() {

		return this.suctionPressure;
	}

	public void setSuctionPressure(String suctionPressure) {

		this.suctionPressure = suctionPressure;
	}

	@Column(name = "uomPressure", length = 50)
	public String getUomPressure() {

		return this.uomPressure;
	}

	public void setUomPressure(String uomPressure) {

		this.uomPressure = uomPressure;
	}

	@Column(name = "primemover_type", length = 50)
	public String getPrimemoverType() {

		return this.primemoverType;
	}

	public void setPrimemoverType(String primemoverType) {

		this.primemoverType = primemoverType;
	}

	@Column(name = "searchCriteria", length = 50)
	public String getSearchCriteria() {

		return this.searchCriteria;
	}

	public void setSearchCriteria(String searchCriteria) {

		this.searchCriteria = searchCriteria;
	}

	@Column(name = "speed", length = 50)
	public String getSpeed() {

		return this.speed;
	}

	public void setSpeed(String speed) {

		this.speed = speed;
	}

	@Column(name = "driver_sizing", length = 50)
	public String getDriverSizing() {

		return this.driverSizing;
	}

	public void setDriverSizing(String driverSizing) {

		this.driverSizing = driverSizing;
	}

	@Column(name = "driver_sizing_perofdp", length = 50)
	public String getDriverSizingPerofdp() {

		return this.driverSizingPerofdp;
	}

	public void setDriverSizingPerofdp(String driverSizingPerofdp) {

		this.driverSizingPerofdp = driverSizingPerofdp;
	}

	@Column(name = "serviceFactor", length = 50)
	public String getServiceFactor() {

		return this.serviceFactor;
	}

	public void setServiceFactor(String serviceFactor) {

		this.serviceFactor = serviceFactor;
	}

	@Column(name = "mounting", length = 50)
	public String getMounting() {

		return this.mounting;
	}

	public void setMounting(String mounting) {

		this.mounting = mounting;
	}

	@Column(name = "effClass", length = 50)
	public String getEffClass() {

		return this.effClass;
	}

	public void setEffClass(String effClass) {

		this.effClass = effClass;
	}

	@Column(name = "specification", length = 50)
	public String getSpecification() {

		return this.specification;
	}

	public void setSpecification(String specification) {

		this.specification = specification;
	}

	@Column(name = "ambientTemp", length = 50)
	public String getAmbientTemp() {

		return this.ambientTemp;
	}

	public void setAmbientTemp(String ambientTemp) {

		this.ambientTemp = ambientTemp;
	}

	@Column(name = "tempClass", length = 50)
	public String getTempClass() {

		return this.tempClass;
	}

	public void setTempClass(String tempClass) {

		this.tempClass = tempClass;
	}

	@Column(name = "pole")
	public Integer getPole() {

		return this.pole;
	}

	public void setPole(Integer pole) {

		this.pole = pole;
	}

	@Column(name = "manufacturer", length = 50)
	public String getManufacturer() {

		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {

		this.manufacturer = manufacturer;
	}

	@Column(name = "liquid_type", length = 50)
	public String getLiquidType() {

		return this.liquidType;
	}

	public void setLiquidType(String liquidType) {

		this.liquidType = liquidType;
	}

	@Column(name = "fluidName", length = 50)
	public String getFluidName() {

		return this.fluidName;
	}

	public void setFluidName(String fluidName) {

		this.fluidName = fluidName;
	}

	@Column(name = "liquid_description", length = 500)
	public String getLiquidDescription() {

		return this.liquidDescription;
	}

	public void setLiquidDescription(String liquidDescription) {

		this.liquidDescription = liquidDescription;
	}

	@Column(name = "max_solid_dia", length = 50)
	public String getMaxSolidDia() {

		return this.maxSolidDia;
	}

	public void setMaxSolidDia(String maxSolidDia) {

		this.maxSolidDia = maxSolidDia;
	}

	@Column(name = "uom_solid_size", length = 50)
	public String getUomSolidSize() {

		return this.uomSolidSize;
	}

	public void setUomSolidSize(String uomSolidSize) {

		this.uomSolidSize = uomSolidSize;
	}

	@Column(name = "max_solid_dia_converted", length = 50)
	public String getMaxSolidDiaConverted() {

		return this.maxSolidDiaConverted;
	}

	public void setMaxSolidDiaConverted(String maxSolidDiaConverted) {

		this.maxSolidDiaConverted = maxSolidDiaConverted;
	}

	@Column(name = "solid_concentration", length = 50)
	public String getSolidConcentration() {

		return this.solidConcentration;
	}

	public void setSolidConcentration(String solidConcentration) {

		this.solidConcentration = solidConcentration;
	}

	@Column(name = "temperature", length = 50)
	public String getTemperature() {

		return this.temperature;
	}

	public void setTemperature(String temperature) {

		this.temperature = temperature;
	}

	@Column(name = "uom_temperature", length = 50)
	public String getUomTemperature() {

		return this.uomTemperature;
	}

	public void setUomTemperature(String uomTemperature) {

		this.uomTemperature = uomTemperature;
	}

	@Column(name = "spgr", length = 50)
	public String getSpgr() {

		return this.spgr;
	}

	public void setSpgr(String spgr) {

		this.spgr = spgr;
	}

	@Column(name = "viscosity", length = 50)
	public String getViscosity() {

		return this.viscosity;
	}

	public void setViscosity(String viscosity) {

		this.viscosity = viscosity;
	}

	@Column(name = "uom_viscosity", length = 50)
	public String getUomViscosity() {

		return this.uomViscosity;
	}

	public void setUomViscosity(String uomViscosity) {

		this.uomViscosity = uomViscosity;
	}

	@Column(name = "vapor_pressure", length = 50)
	public String getVaporPressure() {

		return this.vaporPressure;
	}

	public void setVaporPressure(String vaporPressure) {

		this.vaporPressure = vaporPressure;
	}

	@Column(name = "effModifierImpellerType")
	public Boolean getEffModifierImpellerType() {

		return this.effModifierImpellerType;
	}

	public void setEffModifierImpellerType(Boolean effModifierImpellerType) {

		this.effModifierImpellerType = effModifierImpellerType;
	}

	@Column(name = "effModifierMOC")
	public Boolean getEffModifierMoc() {

		return this.effModifierMoc;
	}

	public void setEffModifierMoc(Boolean effModifierMoc) {

		this.effModifierMoc = effModifierMoc;
	}

	@Column(name = "effModifierStages")
	public Boolean getEffModifierStages() {

		return this.effModifierStages;
	}

	public void setEffModifierStages(Boolean effModifierStages) {

		this.effModifierStages = effModifierStages;
	}

	@Column(name = "effModifierCoating")
	public Boolean getEffModifierCoating() {

		return this.effModifierCoating;
	}

	public void setEffModifierCoating(Boolean effModifierCoating) {

		this.effModifierCoating = effModifierCoating;
	}

	@Column(name = "addEff", length = 50)
	public String getAddEff() {

		return this.addEff;
	}

	public void setAddEff(String addEff) {

		this.addEff = addEff;
	}

	@Column(name = "testing_standard", length = 50)
	public String getTestingStandard() {

		return this.testingStandard;
	}

	public void setTestingStandard(String testingStandard) {

		this.testingStandard = testingStandard;
	}

	@Column(name = "seal", length = 50)
	public String getSeal() {

		return this.seal;
	}

	public void setSeal(String seal) {

		this.seal = seal;
	}

	@Column(name = "lubrication", length = 50)
	public String getLubrication() {

		return this.lubrication;
	}

	public void setLubrication(String lubrication) {

		this.lubrication = lubrication;
	}

	@Column(name = "application", length = 50)
	public String getApplication() {

		return this.application;
	}

	public void setApplication(String application) {

		this.application = application;
	}

	@Column(name = "min_soh", length = 50)
	public String getMinSoh() {

		return this.minSoh;
	}

	public void setMinSoh(String minSoh) {

		this.minSoh = minSoh;
	}

	@Column(name = "max_soh", length = 50)
	public String getMaxSoh() {

		return this.maxSoh;
	}

	public void setMaxSoh(String maxSoh) {

		this.maxSoh = maxSoh;
	}

	@Column(name = "max_flow", length = 50)
	public String getMaxFlow() {

		return this.maxFlow;
	}

	public void setMaxFlow(String maxFlow) {

		this.maxFlow = maxFlow;
	}

	@Column(name = "min_head", length = 50)
	public String getMinHead() {

		return this.minHead;
	}

	public void setMinHead(String minHead) {

		this.minHead = minHead;
	}

	@Column(name = "sumpDepth", length = 50)
	public String getSumpDepth() {

		return this.sumpDepth;
	}

	public void setSumpDepth(String sumpDepth) {

		this.sumpDepth = sumpDepth;
	}

	@Column(name = "DBMSType", length = 50)
	public String getDbmstype() {

		return this.dbmstype;
	}

	public void setDbmstype(String dbmstype) {

		this.dbmstype = dbmstype;
	}

	@Column(name = "fluidLevel", length = 50)
	public String getFluidLevel() {

		return this.fluidLevel;
	}

	public void setFluidLevel(String fluidLevel) {

		this.fluidLevel = fluidLevel;
	}

	@Column(name = "approach", length = 50)
	public String getApproach() {

		return this.approach;
	}

	public void setApproach(String approach) {

		this.approach = approach;
	}

	@Column(name = "series", length = 500)
	public String getSeries() {

		return this.series;
	}

	public void setSeries(String series) {

		this.series = series;
	}

	@Column(name = "pumpModel", length = 50)
	public String getPumpModel() {

		return this.pumpModel;
	}

	public void setPumpModel(String pumpModel) {

		this.pumpModel = pumpModel;
	}

	@Column(name = "perfCurvNo", length = 50)
	public String getPerfCurvNo() {

		return this.perfCurvNo;
	}

	public void setPerfCurvNo(String perfCurvNo) {

		this.perfCurvNo = perfCurvNo;
	}

	@Column(name = "trimDia", length = 50)
	public String getTrimDia() {

		return this.trimDia;
	}

	public void setTrimDia(String trimDia) {

		this.trimDia = trimDia;
	}

	@Column(name = "maxDia", length = 50)
	public String getMaxDia() {

		return this.maxDia;
	}

	public void setMaxDia(String maxDia) {

		this.maxDia = maxDia;
	}

	@Column(name = "minDia", length = 50)
	public String getMinDia() {

		return this.minDia;
	}

	public void setMinDia(String minDia) {

		this.minDia = minDia;
	}

	@Column(name = "diaList", length = 50)
	public String getDiaList() {

		return this.diaList;
	}

	public void setDiaList(String diaList) {

		this.diaList = diaList;
	}

	@Column(name = "trimRatio", length = 50)
	public String getTrimRatio() {

		return this.trimRatio;
	}

	public void setTrimRatio(String trimRatio) {

		this.trimRatio = trimRatio;
	}

	@Column(name = "mocID", length = 50)
	public String getMocId() {

		return this.mocId;
	}

	public void setMocId(String mocId) {

		this.mocId = mocId;
	}

	@Column(name = "rotation", length = 50)
	public String getRotation() {

		return this.rotation;
	}

	public void setRotation(String rotation) {

		this.rotation = rotation;
	}

	@Column(name = "wearRing", length = 50)
	public String getWearRing() {

		return this.wearRing;
	}

	public void setWearRing(String wearRing) {

		this.wearRing = wearRing;
	}

	@Column(name = "feetLocation", length = 50)
	public String getFeetLocation() {

		return this.feetLocation;
	}

	public void setFeetLocation(String feetLocation) {

		this.feetLocation = feetLocation;
	}

	@Column(name = "suctionOrientation", length = 50)
	public String getSuctionOrientation() {

		return this.suctionOrientation;
	}

	public void setSuctionOrientation(String suctionOrientation) {

		this.suctionOrientation = suctionOrientation;
	}

	@Column(name = "dischargeOrientation", length = 50)
	public String getDischargeOrientation() {

		return this.dischargeOrientation;
	}

	public void setDischargeOrientation(String dischargeOrientation) {

		this.dischargeOrientation = dischargeOrientation;
	}

	@Column(name = "flangeType", length = 50)
	public String getFlangeType() {

		return this.flangeType;
	}

	public void setFlangeType(String flangeType) {

		this.flangeType = flangeType;
	}

	@Column(name = "companionFlange", length = 50)
	public String getCompanionFlange() {

		return this.companionFlange;
	}

	public void setCompanionFlange(String companionFlange) {

		this.companionFlange = companionFlange;
	}

	@Column(name = "customer", length = 50)
	public String getCustomer() {

		return this.customer;
	}

	public void setCustomer(String customer) {

		this.customer = customer;
	}

	@Column(name = "consultant", length = 50)
	public String getConsultant() {

		return this.consultant;
	}

	public void setConsultant(String consultant) {

		this.consultant = consultant;
	}

	@Column(name = "endUser", length = 50)
	public String getEndUser() {

		return this.endUser;
	}

	public void setEndUser(String endUser) {

		this.endUser = endUser;
	}

	@Column(name = "project", length = 50)
	public String getProject() {

		return this.project;
	}

	public void setProject(String project) {

		this.project = project;
	}

	@Column(name = "contractor", length = 50)
	public String getContractor() {

		return this.contractor;
	}

	public void setContractor(String contractor) {

		this.contractor = contractor;
	}

	@Column(name = "suppliedBy", length = 50)
	public String getSuppliedBy() {

		return this.suppliedBy;
	}

	public void setSuppliedBy(String suppliedBy) {

		this.suppliedBy = suppliedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "offerDate", length = 10)
	public Date getOfferDate() {

		return this.offerDate;
	}

	public void setOfferDate(Date offerDate) {

		this.offerDate = offerDate;
	}

	@Column(name = "tagNo", length = 50)
	public String getTagNo() {

		return this.tagNo;
	}

	public void setTagNo(String tagNo) {

		this.tagNo = tagNo;
	}

	@Column(name = "offerNo", length = 50)
	public String getOfferNo() {

		return this.offerNo;
	}

	public void setOfferNo(String offerNo) {

		this.offerNo = offerNo;
	}

	@Column(name = "offerRev", length = 50)
	public String getOfferRev() {

		return this.offerRev;
	}

	public void setOfferRev(String offerRev) {

		this.offerRev = offerRev;
	}

	@Column(name = "QUICK_DOC")
	public Boolean getQuickDoc() {

		return this.quickDoc;
	}

	public void setQuickDoc(Boolean quickDoc) {

		this.quickDoc = quickDoc;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

}
