
package com.velotech.fanselection.models;
// Generated Aug 16, 2019 5:49:23 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

import com.google.gson.annotations.Expose;

/**
 * Tbl1401Motortype generated by hbm2java
 */
@Entity
@Table(name = "tbl_1401_motortype")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl1401Motortype implements java.io.Serializable {

	private int id;
	@Expose
	private String series;
	@Expose
	private String description;
	@Expose
	private Integer phase;
	
	private Integer size;
	
	/*
	 * @Expose private String manufacturer;
	 * 
	 * @Expose private Integer frequency;
	 */
//	@Expose
//	private String effClass;
//	@Expose
//	private Integer pole;

	//private String mounting;

	private Tbl80TemplateMaster tbl80TemplateMasterByCsdTemplateId;

	private String csdDrawingNo;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	private String uuid;
	
	

	//private Set<Tbl14PrimemoverMaster> tbl14PrimemoverMasters = new HashSet<Tbl14PrimemoverMaster>(0);

	//private Set<Tbl1410MotorTypeBom> tbl1410MotorTypeBoms = new HashSet<Tbl1410MotorTypeBom>(0);

	public Tbl1401Motortype() {
	}

	public Tbl1401Motortype(int id) {
		this.id = id;
	}

	public Tbl1401Motortype(int id, String series, String createdBy, Date createdDate, String modifiedBy,
			Date modifiedDate, String company, Set<Tbl14PrimemoverMaster> tbl14PrimemoverMasters)
			//Set<Tbl1410MotorTypeBom> tbl1410MotorTypeBoms)
			{
		this.id = id;
		this.series = series;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.company = company;
		//this.tbl14PrimemoverMasters = tbl14PrimemoverMasters;
		//this.tbl1410MotorTypeBoms = tbl1410MotorTypeBoms;

	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@Column(name = "series", length = 50)
	public String getSeries() {

		return this.series;
	}

	public void setSeries(String series) {

		this.series = series;
	}

	@Column(name = "description", length = 255)
	public String getDescription() {

		return description;
	}

	public void setDescription(String description) {

		this.description = description;
	}

	@Column(name = "phase")
	public Integer getPhase() {

		return phase;
	}

	public void setPhase(Integer phase) {

		this.phase = phase;
	}
	
	@Column(name = "size")
	public Integer getSize() {
		return size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

//	@Column(name = "manufacturer")
//	public String getManufacturer() {
//
//		return this.manufacturer;
//	}
//
//	public void setManufacturer(String manufacturer) {
//
//		this.manufacturer = manufacturer;
//	}
//
//	@Column(name = "frequency", length = 10)
//	public Integer getFrequency() {
//
//		return this.frequency;
//	}
//
//	public void setFrequency(Integer frequency) {
//
//		this.frequency = frequency;
//	}

//	@Column(name = "effClass", length = 10)
//	public String getEffClass() {
//
//		return this.effClass;
//	}
//
//	public void setEffClass(String effClass) {
//
//		this.effClass = effClass;
//	}
//
//	@Column(name = "pole")
//	public Integer getPole() {
//
//		return this.pole;
//	}
//
//	public void setPole(Integer pole) {
//
//		this.pole = pole;
//	}

//	@Column(name = "mounting", length = 50)
//	public String getMounting() {
//
//		return this.mounting;
//	}
//
//	public void setMounting(String mounting) {
//
//		this.mounting = mounting;
//	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "csdTemplateId")
	public Tbl80TemplateMaster getTbl80TemplateMasterByCsdTemplateId() {

		return this.tbl80TemplateMasterByCsdTemplateId;
	}

	public void setTbl80TemplateMasterByCsdTemplateId(Tbl80TemplateMaster tbl80TemplateMasterByCsdTemplateId) {

		this.tbl80TemplateMasterByCsdTemplateId = tbl80TemplateMasterByCsdTemplateId;
	}

	@Column(name = "csdDrawingNo", length = 50)
	public String getCsdDrawingNo() {

		return this.csdDrawingNo;
	}

	public void setCsdDrawingNo(String csdDrawingNo) {

		this.csdDrawingNo = csdDrawingNo;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbl1401Motortype")
	public Set<Tbl14PrimemoverMaster> getTbl14PrimemoverMasters() {

		return this.tbl14PrimemoverMasters;
	}

	public void setTbl14PrimemoverMasters(Set<Tbl14PrimemoverMaster> tbl14PrimemoverMasters) {

		this.tbl14PrimemoverMasters = tbl14PrimemoverMasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbl1401Motortype")
	public Set<Tbl1410MotorTypeBom> getTbl1410MotorTypeBoms() {

		return this.tbl1410MotorTypeBoms;
	}

	public void setTbl1410MotorTypeBoms(Set<Tbl1410MotorTypeBom> tbl1410MotorTypeBoms) {

		this.tbl1410MotorTypeBoms = tbl1410MotorTypeBoms;
	}*/

	@Column(name = "uuid", columnDefinition = "uniqueidentifier")
	public String getUuid() {

		return uuid;
	}

	public void setUuid(String uuid) {

		this.uuid = uuid;
	}

}
