
package com.velotech.fanselection.models;
// Generated Jul 18, 2019 12:12:48 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl00ClientMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_00_ClientMaster")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl00ClientMaster implements java.io.Serializable {

	private String clientId;

	private String name;

	private String emailId;

	private Integer modelLicensed;

	private Integer userLicensed;

	private Date subscriptionDate;

	private Boolean active;

	private Boolean sendSummaryEmail;

//	private Tbl00ClientConfiguration tbl00ClientConfiguration;

//	private Tbl00ClientPreferences tbl00ClientPreferences;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl00ClientMaster() {
	}

	public Tbl00ClientMaster(String clientId) {
		this.clientId = clientId;
	}

	public Tbl00ClientMaster(String clientId, String name, String emailId, Integer modelLicensed, Integer userLicensed, Date subscriptionDate,
			Boolean active, Boolean sendSummaryEmail, Tbl00ClientConfiguration tbl00ClientConfiguration,
			Tbl00ClientPreferences tbl00ClientPreferences) {
		this.clientId = clientId;
		this.name = name;
		this.emailId = emailId;
		this.modelLicensed = modelLicensed;
		this.userLicensed = userLicensed;
		this.subscriptionDate = subscriptionDate;
		this.active = active;
		this.sendSummaryEmail = sendSummaryEmail;
//		this.tbl00ClientConfiguration = tbl00ClientConfiguration;
//		this.tbl00ClientPreferences = tbl00ClientPreferences;
	}

	@Id
	@Column(name = "clientId", unique = true, nullable = false, length = 50)
	public String getClientId() {

		return this.clientId;
	}

	public void setClientId(String clientId) {

		this.clientId = clientId;
	}

	@Column(name = "name")
	public String getName() {

		return this.name;
	}

	public void setName(String name) {

		this.name = name;
	}

	@Column(name = "emailId")
	public String getEmailId() {

		return this.emailId;
	}

	public void setEmailId(String emailId) {

		this.emailId = emailId;
	}

	@Column(name = "modelLicensed")
	public Integer getModelLicensed() {

		return this.modelLicensed;
	}

	public void setModelLicensed(Integer modelLicensed) {

		this.modelLicensed = modelLicensed;
	}

	@Column(name = "userLicensed")
	public Integer getUserLicensed() {

		return this.userLicensed;
	}

	public void setUserLicensed(Integer userLicensed) {

		this.userLicensed = userLicensed;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "subscriptionDate", length = 10)
	public Date getSubscriptionDate() {

		return this.subscriptionDate;
	}

	public void setSubscriptionDate(Date subscriptionDate) {

		this.subscriptionDate = subscriptionDate;
	}

	@Column(name = "active")
	public Boolean getActive() {

		return this.active;
	}

	public void setActive(Boolean active) {

		this.active = active;
	}

	@Column(name = "sendSummaryEmail")
	public Boolean getSendSummaryEmail() {

		return this.sendSummaryEmail;
	}

	public void setSendSummaryEmail(Boolean sendSummaryEmail) {

		this.sendSummaryEmail = sendSummaryEmail;
	}

	/*@OneToOne(fetch = FetchType.LAZY, mappedBy = "tbl00ClientMaster")
	public Tbl00ClientConfiguration getTbl00ClientConfiguration() {

		return this.tbl00ClientConfiguration;
	}

	public void setTbl00ClientConfiguration(Tbl00ClientConfiguration tbl00ClientConfiguration) {

		this.tbl00ClientConfiguration = tbl00ClientConfiguration;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "tbl00ClientMaster")
	public Tbl00ClientPreferences getTbl00ClientPreferences() {

		return this.tbl00ClientPreferences;
	}

	public void setTbl00ClientPreferences(Tbl00ClientPreferences tbl00ClientPreferences) {

		this.tbl00ClientPreferences = tbl00ClientPreferences;
	}
*/
	public String getCreatedBy() {

		return createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {

		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	public String getModifiedBy() {

		return modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDate() {

		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	public String getCompany() {

		return company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

}
