
package com.velotech.fanselection.models;
// Generated 23 Mar, 2020 11:44:34 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;
/**
 * Tbl52RegistrationTable generated by hbm2java
 */
@Entity
@Table(name = "tbl_52_RegistrationTable")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl52RegistrationTable implements java.io.Serializable {

	private int id;

	private String name;

	private String emailId;

	private String organizationName;

	private String purpose;

	private String provider;
	
	private String contactNo;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl52RegistrationTable() {
	}

	public Tbl52RegistrationTable(int id) {
		this.id = id;
	}

	public Tbl52RegistrationTable(int id, String name, String emailId, String organizationName, String purpose, String provider) {
		this.id = id;
		this.name = name;
		this.emailId = emailId;
		this.organizationName = organizationName;
		this.purpose = purpose;
		this.provider = provider;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@Column(name = "name", length = 250)
	public String getName() {

		return this.name;
	}

	public void setName(String name) {

		this.name = name;
	}

	@Column(name = "email_id", length = 250)
	public String getEmailId() {

		return this.emailId;
	}

	public void setEmailId(String emailId) {

		this.emailId = emailId;
	}

	@Column(name = "organizationName", length = 250)
	public String getOrganizationName() {

		return this.organizationName;
	}

	public void setOrganizationName(String organizationName) {

		this.organizationName = organizationName;
	}

	@Column(name = "purpose", length = 250)
	public String getPurpose() {

		return this.purpose;
	}

	public void setPurpose(String purpose) {

		this.purpose = purpose;
	}

	@Column(name = "provider", length = 250)
	public String getProvider() {

		return this.provider;
	}

	public void setProvider(String provider) {

		this.provider = provider;
	}

	@Column(name = "contactNo", length = 250)
	public String getContactNo() {
		return contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

}
