
package com.velotech.fanselection.models;
// Generated 30 Dec, 2022 2:21:10 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl90SolarParameterValue generated by hbm2java
 */
@Entity
@Table(name = "tbl_90_parameterValue"/*
										 * , uniqueConstraints
										 * = @UniqueConstraint(columnNames = {
										 * "parameter", "company" })
										 */)
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl90ParameterValue implements java.io.Serializable {

	private int id;

	private String parameter;

	private String value;
	
	private String parameterLabel;

	private Integer sequence;

	private Boolean isExpression;

	private Boolean isUserInput;

	private String suffix;

	private String prefix;

	private String uuid;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl90ParameterValue() {
	}

	public Tbl90ParameterValue(int id) {
		this.id = id;
	}

	public Tbl90ParameterValue(String parameter, String value, Integer sequence, Boolean isExpression, String suffix, String prefix, String uuid,
			String createdBy, Date createdDate, String modifiedBy, Date modifiedDate, String company,Boolean isUserInput) {
		super();
		this.parameter = parameter;
		this.value = value;
		this.sequence = sequence;
		this.isExpression = isExpression;
		this.suffix = suffix;
		this.prefix = prefix;
		this.uuid = uuid;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.company = company;
		this.isUserInput=isUserInput;
	}

	public Tbl90ParameterValue(String uuid, String parameter, String value, Integer sequence, Boolean isExpression, String suffix, String prefix,Boolean isUserInput) {

		this.uuid = uuid;
		this.parameter = parameter;
		this.value = value;
		this.sequence = sequence;
		this.isExpression = isExpression;
		this.suffix = suffix;
		this.prefix = prefix;
		this.isUserInput=isUserInput;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@Column(name = "parameter")
	public String getParameter() {

		return this.parameter;
	}

	public void setParameter(String parameter) {

		this.parameter = parameter;
	}

	@Column(name = "value", columnDefinition = "TEXT")
	public String getValue() {

		return this.value;
	}

	public void setValue(String value) {

		this.value = value;
	}
	
	@Column(name = "parameterLabel")
	public String getParameterLabel() {
		return parameterLabel;
	}

	public void setParameterLabel(String parameterLabel) {
		this.parameterLabel = parameterLabel;
	}

	@Column(name = "sequence")
	public Integer getSequence() {

		return this.sequence;
	}

	public void setSequence(Integer sequence) {

		this.sequence = sequence;
	}

	@Column(name = "isExpression")
	public Boolean getIsExpression() {

		return this.isExpression;
	}

	public void setIsExpression(Boolean isExpression) {

		this.isExpression = isExpression;
	}

	@Column(name = "isUserInput")
	public Boolean getIsUserInput() {

		return isUserInput;
	}

	public void setIsUserInput(Boolean isUserInput) {

		this.isUserInput = isUserInput;
	}

	@Column(name = "suffix", length = 50)
	public String getSuffix() {

		return this.suffix;
	}

	public void setSuffix(String suffix) {

		this.suffix = suffix;
	}

	@Column(name = "prefix", length = 50)
	public String getPrefix() {

		return this.prefix;
	}

	public void setPrefix(String prefix) {

		this.prefix = prefix;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@Column(name = "uuid")
	public String getUuid() {

		return uuid;
	}

	public void setUuid(String uuid) {

		this.uuid = uuid;
	}

	@Override
	public String toString() {
		return "Tbl90ParameterValue [id=" + id + ", parameter=" + parameter + ", value=" + value + ", sequence="
				+ sequence + ", isExpression=" + isExpression + ", isUserInput=" + isUserInput + ", suffix=" + suffix
				+ ", prefix=" + prefix + ", uuid=" + uuid + ", createdBy=" + createdBy + ", createdDate=" + createdDate
				+ ", modifiedBy=" + modifiedBy + ", modifiedDate=" + modifiedDate + ", company=" + company + "]";
	}
	
}
