
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl01VariantMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_01_variant_master")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl01VariantMaster implements java.io.Serializable {

	private int id;

	private Tbl01Fantype tbl01Fantype;

	private String variant;

	private String variantCode;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl01VariantMaster() {
	}

	public Tbl01VariantMaster(int id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seriesId")
	public Tbl01Fantype getTbl01Fantype() {
		return tbl01Fantype;
	}

	public void setTbl01Fantype(Tbl01Fantype tbl01Fantype) {
		this.tbl01Fantype = tbl01Fantype;
	}

	@Column(name = "variant")
	public String getVariant() {

		return this.variant;
	}

	public void setVariant(String variant) {

		this.variant = variant;
	}

	@Column(name = "variantCode", length = 50)
	public String getVariantCode() {

		return variantCode;
	}

	public void setVariantCode(String variantCode) {

		this.variantCode = variantCode;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

}
