
package com.velotech.fanselection.models;
// Generated Jun 7, 2019 10:48:23 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl01VariantLine generated by hbm2java
 */
@Entity
@Table(name = "tbl_01_variant_line")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl01VariantLine implements java.io.Serializable {

	private int id;

	private Tbl01VariantMaster tbl01VariantMaster;

	private String parameter;

	private String value;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl01VariantLine() {
	}

	public Tbl01VariantLine(int id) {
		this.id = id;
	}

	public Tbl01VariantLine(int id, Tbl01VariantMaster tbl01VariantMaster, String parameter, String value) {
		this.id = id;
		this.tbl01VariantMaster = tbl01VariantMaster;
		this.parameter = parameter;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "variantId")
	public Tbl01VariantMaster getTbl01VariantMaster() {

		return this.tbl01VariantMaster;
	}

	public void setTbl01VariantMaster(Tbl01VariantMaster tbl01VariantMaster) {

		this.tbl01VariantMaster = tbl01VariantMaster;
	}

	@Column(name = "parameter", length = 50)
	public String getParameter() {

		return this.parameter;
	}

	public void setParameter(String parameter) {

		this.parameter = parameter;
	}

	@Column(name = "value", length = 50)
	public String getValue() {

		return this.value;
	}

	public void setValue(String value) {

		this.value = value;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}
}
