
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl03MocMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_03_moc_master")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl03MocMaster implements java.io.Serializable {

	private int mocMasterId;

	private Tbl01Fantype tbl01fantype;

	private String mocStd;

	private Boolean stdSupply;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl03MocMaster() {
	}

	public Tbl03MocMaster(int mocMasterId) {
		this.mocMasterId = mocMasterId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "moc_master_id", unique = true, nullable = false)
	public int getMocMasterId() {

		return this.mocMasterId;
	}

	public void setMocMasterId(int mocMasterId) {

		this.mocMasterId = mocMasterId;
	}

	

	@Column(name = "mocStd", length = 50)
	public String getMocStd() {

		return this.mocStd;
	}

	public void setMocStd(String mocStd) {

		this.mocStd = mocStd;
	}

	@Column(name = "stdSupply")
	public Boolean getStdSupply() {

		return this.stdSupply;
	}

	public void setStdSupply(Boolean stdSupply) {

		this.stdSupply = stdSupply;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seriesId")
	public Tbl01Fantype getTbl01fantype() {
		return tbl01fantype;
	}

	public void setTbl01fantype(Tbl01Fantype tbl01fantype) {
		this.tbl01fantype = tbl01fantype;
	}

}
