
package com.velotech.fanselection.models;
// Generated Jul 18, 2019 12:12:48 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Tbl00ClientConfiguration generated by hbm2java
 */
@Entity
@Table(name = "tbl_00_clientConfiguration")
public class Tbl00ClientConfiguration implements java.io.Serializable {

	private String clientId;

	private Tbl00ClientMaster tbl00ClientMaster;

	private String emailId;

	private String emailPassword;

	private String emailOutgoingPort;

	private String sslCertificate;

	private String smsApi;

	public Tbl00ClientConfiguration() {
	}

	public Tbl00ClientConfiguration(Tbl00ClientMaster tbl00ClientMaster) {
		this.tbl00ClientMaster = tbl00ClientMaster;
	}

	public Tbl00ClientConfiguration(Tbl00ClientMaster tbl00ClientMaster, String emailId, String emailPassword, String emailOutgoingPort,
			String sslCertificate, String smsApi) {
		this.tbl00ClientMaster = tbl00ClientMaster;
		this.emailId = emailId;
		this.emailPassword = emailPassword;
		this.emailOutgoingPort = emailOutgoingPort;
		this.sslCertificate = sslCertificate;
		this.smsApi = smsApi;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "tbl00ClientMaster"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "clientId", unique = true, nullable = false, length = 50)
	public String getClientId() {

		return this.clientId;
	}

	public void setClientId(String clientId) {

		this.clientId = clientId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Tbl00ClientMaster getTbl00ClientMaster() {

		return this.tbl00ClientMaster;
	}

	public void setTbl00ClientMaster(Tbl00ClientMaster tbl00ClientMaster) {

		this.tbl00ClientMaster = tbl00ClientMaster;
	}

	@Column(name = "emailId")
	public String getEmailId() {

		return this.emailId;
	}

	public void setEmailId(String emailId) {

		this.emailId = emailId;
	}

	@Column(name = "emailPassword", length = 50)
	public String getEmailPassword() {

		return this.emailPassword;
	}

	public void setEmailPassword(String emailPassword) {

		this.emailPassword = emailPassword;
	}

	@Column(name = "emailOutgoingPort", length = 50)
	public String getEmailOutgoingPort() {

		return this.emailOutgoingPort;
	}

	public void setEmailOutgoingPort(String emailOutgoingPort) {

		this.emailOutgoingPort = emailOutgoingPort;
	}

	@Column(name = "sslCertificate", columnDefinition = "TEXT")
	public String getSslCertificate() {

		return this.sslCertificate;
	}

	public void setSslCertificate(String sslCertificate) {

		this.sslCertificate = sslCertificate;
	}

	@Column(name = "smsAPI", columnDefinition = "TEXT")
	public String getSmsApi() {

		return this.smsApi;
	}

	public void setSmsApi(String smsApi) {

		this.smsApi = smsApi;
	}

}
