
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tbl00TreeMenuMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_00_treeMenuMaster")
public class Tbl00TreeMenuMaster implements java.io.Serializable {

	private int id;

	private Tbl00TreeMenuMaster tbl00TreeMenuMaster;

	private String text;

	private boolean leaf;

	private Double sequence;

	private Boolean expanded;

	private Integer departmentId;

	private Integer applicationId;

	private String code;

	private String title;

	private String xtype;

	private String company;

	private String helpText;

	private Set<Tbl00TreeMenuMaster> tbl00TreeMenuMasters = new HashSet<Tbl00TreeMenuMaster>(0);

	public Tbl00TreeMenuMaster() {
	}

	public Tbl00TreeMenuMaster(int id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parentId")
	public Tbl00TreeMenuMaster getTbl00TreeMenuMaster() {

		return this.tbl00TreeMenuMaster;
	}

	public void setTbl00TreeMenuMaster(Tbl00TreeMenuMaster tbl00TreeMenuMaster) {

		this.tbl00TreeMenuMaster = tbl00TreeMenuMaster;
	}

	@Column(name = "text", nullable = false)
	public String getText() {

		return this.text;
	}

	public void setText(String text) {

		this.text = text;
	}

	@Column(name = "leaf", nullable = false)
	public boolean isLeaf() {

		return this.leaf;
	}

	public void setLeaf(boolean leaf) {

		this.leaf = leaf;
	}

	@Column(name = "sequence", precision = 18)
	public Double getSequence() {

		return this.sequence;
	}

	public void setSequence(Double sequence) {

		this.sequence = sequence;
	}

	@Column(name = "expanded")
	public Boolean getExpanded() {

		return this.expanded;
	}

	public void setExpanded(Boolean expanded) {

		this.expanded = expanded;
	}

	@Column(name = "departmentId")
	public Integer getDepartmentId() {

		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {

		this.departmentId = departmentId;
	}

	@Column(name = "applicationId")
	public Integer getApplicationId() {

		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {

		this.applicationId = applicationId;
	}

	@Column(name = "code", length = 50)
	public String getCode() {

		return this.code;
	}

	public void setCode(String code) {

		this.code = code;
	}

	@Column(name = "title")
	public String getTitle() {

		return this.title;
	}

	public void setTitle(String title) {

		this.title = title;
	}

	@Column(name = "xtype")
	public String getXtype() {

		return this.xtype;
	}

	public void setXtype(String xtype) {

		this.xtype = xtype;
	}

	@Column(name = "company", nullable = false)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@Column(name = "helpText")
	public String getHelpText() {

		return this.helpText;
	}

	public void setHelpText(String helpText) {

		this.helpText = helpText;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbl00TreeMenuMaster")
	public Set<Tbl00TreeMenuMaster> getTbl00TreeMenuMasters() {

		return this.tbl00TreeMenuMasters;
	}

	public void setTbl00TreeMenuMasters(Set<Tbl00TreeMenuMaster> tbl00TreeMenuMasters) {

		this.tbl00TreeMenuMasters = tbl00TreeMenuMasters;
	}

}
