
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl03GenericBom generated by hbm2java
 */
@Entity
@Table(name = "tbl_03_genericBOM")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl03GenericBom implements java.io.Serializable {

	private int genericBomId;

	private Tbl01Fantype tbl01Fantype;

	//private Tbl1401Motortype tbl1401Motortype;

	private String mocStd;

	private String systemPressure;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	private String shaftGroup;

	private Integer minStage;

	private Integer maxStage;

	private Integer variantId;
	
	private Integer sequence;

	public Tbl03GenericBom() {
	}

	public Tbl03GenericBom(int genericBomId) {
		this.genericBomId = genericBomId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "generic_bom_id", unique = true, nullable = false)
	public int getGenericBomId() {

		return this.genericBomId;
	}

	public void setGenericBomId(int genericBomId) {

		this.genericBomId = genericBomId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seriesId")
	public Tbl01Fantype getTbl01Fantype() {
		return tbl01Fantype;
	}

	public void setTbl01Fantype(Tbl01Fantype tbl01Fantype) {
		this.tbl01Fantype = tbl01Fantype;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "motorSeriesId")
	public Tbl1401Motortype getTbl1401Motortype() {

		return this.tbl1401Motortype;
	}

	public void setTbl1401Motortype(Tbl1401Motortype tbl1401Motortype) {

		this.tbl1401Motortype = tbl1401Motortype;
	}*/

	@Column(name = "mocStd", length = 50)
	public String getMocStd() {

		return this.mocStd;
	}

	

	public void setMocStd(String mocStd) {

		this.mocStd = mocStd;
	}

	@Column(name = "systemPressure", length = 50)
	public String getSystemPressure() {

		return this.systemPressure;
	}

	public void setSystemPressure(String systemPressure) {

		this.systemPressure = systemPressure;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@Column(name = "shaftGroup", length = 50)
	public String getShaftGroup() {

		return this.shaftGroup;
	}

	public void setShaftGroup(String shaftGroup) {

		this.shaftGroup = shaftGroup;
	}

	@Column(name = "minStage")
	public Integer getMinStage() {

		return this.minStage;
	}

	public void setMinStage(Integer minStage) {

		this.minStage = minStage;
	}

	@Column(name = "maxStage")
	public Integer getMaxStage() {

		return this.maxStage;
	}

	public void setMaxStage(Integer maxStage) {

		this.maxStage = maxStage;
	}
	
	@Column(name = "sequence")
	public Integer getSequence() {
		return sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}
	
	

}
