
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl03GenericBomData generated by hbm2java
 */
@Entity
@Table(name = "tbl_03_genericBOM_data")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl03GenericBomData implements java.io.Serializable {

	private int genericBomDataId;

	private Tbl03GenericBom tbl03GenericBom;

	private Tbl03ItemMaster tbl03ItemMaster;

	private Tbl03MaterialMaster tbl03MaterialMaster;

	private String itemNo;

	private String description;

	private Double qty;

	private String qtyExpression;

	private String qtyUom;

	private Boolean showInDatasheet;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;
	
	private Integer sequence;
	

	public Tbl03GenericBomData() {
	}

	public Tbl03GenericBomData(int genericBomDataId) {
		this.genericBomDataId = genericBomDataId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "generic_bom_data_id", unique = true, nullable = false)
	public int getGenericBomDataId() {

		return this.genericBomDataId;
	}

	public void setGenericBomDataId(int genericBomDataId) {

		this.genericBomDataId = genericBomDataId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "generic_bom_id")
	public Tbl03GenericBom getTbl03GenericBom() {

		return this.tbl03GenericBom;
	}

	public void setTbl03GenericBom(Tbl03GenericBom tbl03GenericBom) {

		this.tbl03GenericBom = tbl03GenericBom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public Tbl03ItemMaster getTbl03ItemMaster() {

		return this.tbl03ItemMaster;
	}

	public void setTbl03ItemMaster(Tbl03ItemMaster tbl03ItemMaster) {

		this.tbl03ItemMaster = tbl03ItemMaster;
	}

	@Column(name = "itemNo", length = 10)
	public String getItemNo() {

		return this.itemNo;
	}

	public void setItemNo(String itemNo) {

		this.itemNo = itemNo;
	}

	@Column(name = "description")
	public String getDescription() {

		return this.description;
	}

	public void setDescription(String description) {

		this.description = description;
	}

	@Column(name = "qty", precision = 18)
	public Double getQty() {

		return this.qty;
	}

	public void setQty(Double qty) {

		this.qty = qty;
	}

	@Column(name = "qtyExpression")
	public String getQtyExpression() {

		return qtyExpression;
	}

	public void setQtyExpression(String qtyExpression) {

		this.qtyExpression = qtyExpression;
	}

	@Column(name = "qtyUOM", length = 50)
	public String getQtyUom() {

		return this.qtyUom;
	}

	public void setQtyUom(String qtyUom) {

		this.qtyUom = qtyUom;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@Column(name = "showInDatasheet")
	public Boolean getShowInDatasheet() {

		return showInDatasheet;
	}

	public void setShowInDatasheet(Boolean showInDatasheet) {

		this.showInDatasheet = showInDatasheet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "materialId")
	public Tbl03MaterialMaster getTbl03MaterialMaster() {

		return this.tbl03MaterialMaster;
	}

	public void setTbl03MaterialMaster(Tbl03MaterialMaster tbl03MaterialMaster) {

		this.tbl03MaterialMaster = tbl03MaterialMaster;
	}
	
	@Column(name = "sequence")
	public Integer getSequence() {
		return sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}
	
	

}
