
package com.velotech.fanselection.models;
// Generated 9 Nov, 2019 2:41:01 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl01ProductMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_01_product_master")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl01ProductMaster implements java.io.Serializable {

	private int id;

	private Tbl01ProductTypeMaster tbl01ProductTypeMaster;
	
	private String uuid;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	private Tbl14PrimemoverMaster tbl14PrimemoverMaster;

	public Tbl01ProductMaster() {
	}

	public Tbl01ProductMaster(int id) {
		this.id = id;
	}

	public Tbl01ProductMaster(int id, Tbl01ProductTypeMaster tbl01ProductTypeMaster, String createdBy, Date createdDate, String modifiedBy,
			Date modifiedDate, String company, Tbl14PrimemoverMaster tbl14PrimemoverMaster) {
		this.id = id;
		this.tbl01ProductTypeMaster = tbl01ProductTypeMaster;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.company = company;
		this.tbl14PrimemoverMaster = tbl14PrimemoverMaster;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productTypeMasterId")
	public Tbl01ProductTypeMaster getTbl01ProductTypeMaster() {

		return this.tbl01ProductTypeMaster;
	}

	public void setTbl01ProductTypeMaster(Tbl01ProductTypeMaster tbl01ProductTypeMaster) {

		this.tbl01ProductTypeMaster = tbl01ProductTypeMaster;
	}
	@Column(name = "uuid", columnDefinition = "uniqueidentifier") 
	public String getUuid() {

		return uuid;
	}

	public void setUuid(String uuid) {

		this.uuid = uuid;
	}
	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "tbl01ProductMaster")
	public Tbl14PrimemoverMaster getTbl14PrimemoverMaster() {

		return this.tbl14PrimemoverMaster;
	}

	public void setTbl14PrimemoverMaster(Tbl14PrimemoverMaster tbl14PrimemoverMaster) {

		this.tbl14PrimemoverMaster = tbl14PrimemoverMaster;
	}

}
