
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.ParamDef;
import org.hibernate.annotations.Parameter;

import com.google.gson.annotations.Expose;

/**
 * Tbl14PrimemoverMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_14_primemover_master")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl14PrimemoverMaster implements java.io.Serializable {

	@Expose
	private int primemoverId;

	private Tbl1401Motortype tbl1401Motortype;

	private Tbl01ProductMaster tbl01ProductMaster;

	private Tbl14FrameMaster tbl14FrameMaster;

	@Expose
	private String uuid;

	@Expose
	private String series;

	@Expose
	private String framesize;

	@Expose
	private String moc;

	@Expose
	private String effClass;

	@Expose
	private Integer pole;

	@Expose
	private Integer voltage;

	@Expose
	private Double startingCurrent;
	@Expose
	private String startingTorque;
	@Expose
	private String voltageTolerance;
	
	private Double ratedCurrent;

	private Double maxCurrent;
	
	@Expose
	private Integer phase;
	
	@Expose
	private String manufacturer;
	@Expose
	private Integer frequency;
	
	private String mounting;

	@Expose
	private Double power;

	@Expose
	private Double speed;

	@Expose
	private String specification;

	@Expose
	private String primemoverType;

	@Expose
	private String weight;
	
	@Expose
	private Double eff;

	private String articleNo;

	private Double price;

	private String shaftDia;

	private Double ambientTemp;

	private String tempRiseClass;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;
	@Expose
	private Double powerHp;

	//private String primeMoverSize;

	@Expose
	private String modelName;

	private String startingMethod;
	@Expose
	private Integer motorCableLength;

	private String maximumCableSize;

	private String insulationClass;

	private String enclousreClass;

	// private Set<Tbl14PrimemoverData> tbl14PrimemoverDatas = new
	// HashSet<Tbl14PrimemoverData>(0);

	public Tbl14PrimemoverMaster() {
	}

	public Tbl14PrimemoverMaster(int primemoverId) {
		this.primemoverId = primemoverId;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "tbl01ProductMaster"))
	@Id
	@Column(name = "primemover_id", unique = true, nullable = false)
	public int getPrimemoverId() {

		return this.primemoverId;
	}

	public void setPrimemoverId(int primemoverId) {

		this.primemoverId = primemoverId;
	}

	@ManyToOne(fetch = FetchType.LAZY)

	@JoinColumn(name = "motorSeriesId")
	public Tbl1401Motortype getTbl1401Motortype() {

		return this.tbl1401Motortype;
	}

	public void setTbl1401Motortype(Tbl1401Motortype tbl1401Motortype) {

		this.tbl1401Motortype = tbl1401Motortype;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Tbl01ProductMaster getTbl01ProductMaster() {

		return this.tbl01ProductMaster;
	}

	public void setTbl01ProductMaster(Tbl01ProductMaster tbl01ProductMaster) {

		this.tbl01ProductMaster = tbl01ProductMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)

	@JoinColumn(name = "frameMasterId")

	public Tbl14FrameMaster getTbl14FrameMaster() {
		return tbl14FrameMaster;
	}

	public void setTbl14FrameMaster(Tbl14FrameMaster tbl14FrameMaster) {
		this.tbl14FrameMaster = tbl14FrameMaster;
	}

	@Column(name = "series")
	public String getSeries() {

		return this.series;
	}

	public void setSeries(String series) {

		this.series = series;
	}

	@Column(name = "framesize", length = 50)
	public String getFramesize() {

		return this.framesize;
	}

	public void setFramesize(String framesize) {

		this.framesize = framesize;
	}

	@Column(name = "moc", length = 50)
	public String getMoc() {

		return this.moc;
	}

	public void setMoc(String moc) {

		this.moc = moc;
	}


	@Column(name = "power", precision = 18)
	public Double getPower() {

		return this.power;
	}

	public void setPower(Double power) {

		this.power = power;
	}

	@Column(name = "speed", precision = 18)
	public Double getSpeed() {

		return this.speed;
	}

	public void setSpeed(Double speed) {

		this.speed = speed;
	}
	
	@Column(name = "voltage")
	public Integer getVoltage() {
		return voltage;
	}

	public void setVoltage(Integer voltage) {
		this.voltage = voltage;
	}


	@Column(name = "startingCurrent", precision = 18)
	public Double getStartingCurrent() {
		return startingCurrent;
	}

	public void setStartingCurrent(Double startingCurrent) {
		this.startingCurrent = startingCurrent;
	}

	@Column(name = "startingTorque", length = 50)
	public String getStartingTorque() {
		return startingTorque;
	}

	public void setStartingTorque(String startingTorque) {
		this.startingTorque = startingTorque;
	}

	@Column(name = "voltageTolerance", length = 50)
	public String getVoltageTolerance() {
		return voltageTolerance;
	}

	public void setVoltageTolerance(String voltageTolerance) {
		this.voltageTolerance = voltageTolerance;
	}

	@Column(name = "ratedCurrent", precision = 18)
	public Double getRatedCurrent() {
		return ratedCurrent;
	}

	public void setRatedCurrent(Double ratedCurrent) {
		this.ratedCurrent = ratedCurrent;
	}

	@Column(name = "maxCurrent", precision = 18)
	public Double getMaxCurrent() {
		return maxCurrent;
	}

	public void setMaxCurrent(Double maxCurrent) {
		this.maxCurrent = maxCurrent;
	}

	@Column(name = "phase")
	public Integer getPhase() {
		return phase;
	}

	
	public void setPhase(Integer phase) {
		this.phase = phase;
	}

	@Column(name = "manufacturer", length = 50)
	public String getManufacturer() {
		return manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Column(name = "frequency")
	public Integer getFrequency() {
		return frequency;
	}

	public void setFrequency(Integer frequency) {
		this.frequency = frequency;
	}

	@Column(name = "mounting", length = 50)
	public String getMounting() {
		return mounting;
	}

	public void setMounting(String mounting) {
		this.mounting = mounting;
	}

	@Column(name = "specification")
	public String getSpecification() {

		return this.specification;
	}

	public void setSpecification(String specification) {

		this.specification = specification;
	}

	@Column(name = "primemover_type", length = 50)
	public String getPrimemoverType() {

		return this.primemoverType;
	}

	public void setPrimemoverType(String primemoverType) {

		this.primemoverType = primemoverType;
	}

	@Column(name = "weight", length = 10)
	public String getWeight() {

		return this.weight;
	}

	public void setWeight(String weight) {

		this.weight = weight;
	}
	
	@Column(name = "eff", precision = 18)
	public Double getEff() {
		return eff;
	}

	public void setEff(Double eff) {
		this.eff = eff;
	}

	@Column(name = "articleNo", length = 50)
	public String getArticleNo() {

		return this.articleNo;
	}

	public void setArticleNo(String articleNo) {

		this.articleNo = articleNo;
	}

	@Column(name = "price", precision = 18)
	public Double getPrice() {

		return this.price;
	}

	public void setPrice(Double price) {

		this.price = price;
	}

	@Column(name = "shaftDia", length = 50)
	public String getShaftDia() {

		return this.shaftDia;
	}

	public void setShaftDia(String shaftDia) {

		this.shaftDia = shaftDia;
	}

	@Column(name = "ambientTemp", precision = 18)
	public Double getAmbientTemp() {

		return this.ambientTemp;
	}

	public void setAmbientTemp(Double ambientTemp) {

		this.ambientTemp = ambientTemp;
	}

	@Column(name = "tempRiseClass", length = 50)
	public String getTempRiseClass() {

		return this.tempRiseClass;
	}

	public void setTempRiseClass(String tempRiseClass) {

		this.tempRiseClass = tempRiseClass;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@Column(name = "powerHp", precision = 18, scale = 4)
	public Double getPowerHp() {

		return this.powerHp;
	}

	public void setPowerHp(Double powerHp) {

		this.powerHp = powerHp;
	}

//	@Column(name = "primeMoverSize")
//	public String getPrimeMoverSize() {
//
//		return primeMoverSize;
//	}
//
//	public void setPrimeMoverSize(String primeMoverSize) {
//
//		this.primeMoverSize = primeMoverSize;
//	}

	@Column(name = "modelName")
	public String getModelName() {

		return modelName;
	}

	public void setModelName(String modelName) {

		this.modelName = modelName;
	}

	@Column(name = "startingMethod")
	public String getStartingMethod() {

		return startingMethod;
	}

	public void setStartingMethod(String startingMethod) {

		this.startingMethod = startingMethod;
	}

	@Column(name = "motorCableLength")
	public Integer getMotorCableLength() {

		return motorCableLength;
	}

	public void setMotorCableLength(Integer motorCableLength) {

		this.motorCableLength = motorCableLength;
	}

	@Column(name = "maximumCableSize")
	public String getMaximumCableSize() {

		return maximumCableSize;
	}

	public void setMaximumCableSize(String maximumCableSize) {

		this.maximumCableSize = maximumCableSize;
	}

	@Column(name = "insulationClass")
	public String getInsulationClass() {
		return insulationClass;
	}

	public void setInsulationClass(String insulationClass) {
		this.insulationClass = insulationClass;
	}

	@Column(name = "enclousreClass")
	public String getEnclousreClass() {
		return enclousreClass;
	}

	public void setEnclousreClass(String enclousreClass) {
		this.enclousreClass = enclousreClass;
	}

	@Column(name = "uuid", columnDefinition = "uniqueidentifier")
	public String getUuid() {

		return uuid;
	}

	public void setUuid(String uuid) {

		this.uuid = uuid;
	}

	@Column(name = "pole")
	public Integer getPole() {
		return pole;
	}

	public void setPole(Integer pole) {
		this.pole = pole;
	}

	@Column(name = "effClass", length = 50)
	public String getEffClass() {
		return effClass;
	}

	public void setEffClass(String effClass) {
		this.effClass = effClass;
	}

}
