
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl23OfferShare generated by hbm2java
 */
@Entity
@Table(name = "tbl_23_offerShare")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl23OfferShare implements java.io.Serializable {

	private int id;

	private Tbl23OfferRev tbl23OfferRev;

	private Tbl52Usermaster tbl52Usermaster;

	private Boolean isShare;

	private Boolean isReadOnly;

	private Boolean isEmail;

	private Boolean isSms;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl23OfferShare() {
	}

	public Tbl23OfferShare(int id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "offerNoId")
	public Tbl23OfferRev getTbl23OfferRev() {

		return this.tbl23OfferRev;
	}

	public void setTbl23OfferRev(Tbl23OfferRev tbl23OfferRev) {

		this.tbl23OfferRev = tbl23OfferRev;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "login_id")
	public Tbl52Usermaster getTbl52Usermaster() {

		return this.tbl52Usermaster;
	}

	public void setTbl52Usermaster(Tbl52Usermaster tbl52Usermaster) {

		this.tbl52Usermaster = tbl52Usermaster;
	}

	@Column(name = "isShare")
	public Boolean getIsShare() {

		return this.isShare;
	}

	public void setIsShare(Boolean isShare) {

		this.isShare = isShare;
	}

	@Column(name = "isReadOnly")
	public Boolean getIsReadOnly() {

		return this.isReadOnly;
	}

	public void setIsReadOnly(Boolean isReadOnly) {

		this.isReadOnly = isReadOnly;
	}

	@Column(name = "isEmail")
	public Boolean getIsEmail() {

		return this.isEmail;
	}

	public void setIsEmail(Boolean isEmail) {

		this.isEmail = isEmail;
	}

	@Column(name = "isSms")
	public Boolean getIsSms() {

		return this.isSms;
	}

	public void setIsSms(Boolean isSms) {

		this.isSms = isSms;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

}
