
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

import com.google.gson.annotations.Expose;

/**
 * Tbl25CustomerMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_25_customerMaster")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl25CustomerMaster implements java.io.Serializable {

	private int customerId;

	private Tbl28CompanyMaster tbl28CompanyMaster;
	@Expose
	private String customerName;
	@Expose
	private String customerAddress1;
	@Expose
	private String customerAddress2;
	@Expose
	private String city;
	@Expose
	private String state;
	@Expose
	private String country;
	@Expose
	private String pincode;

	private String type;

	private String category;
	@Expose
	private String website;

	private String fax;
	@Expose
	private String email;
	@Expose
	private String sap_code;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl25CustomerMaster() {
	}

	public Tbl25CustomerMaster(int customerId) {
		this.customerId = customerId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "customerId", unique = true, nullable = false)
	public int getCustomerId() {

		return this.customerId;
	}

	public void setCustomerId(int customerId) {

		this.customerId = customerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subCompany")
	public Tbl28CompanyMaster getTbl28CompanyMaster() {

		return this.tbl28CompanyMaster;
	}

	public void setTbl28CompanyMaster(Tbl28CompanyMaster tbl28CompanyMaster) {

		this.tbl28CompanyMaster = tbl28CompanyMaster;
	}

	@Column(name = "customerName")
	public String getCustomerName() {

		return this.customerName;
	}

	public void setCustomerName(String customerName) {

		this.customerName = customerName;
	}

	@Column(name = "customerAddress1")
	public String getCustomerAddress1() {

		return this.customerAddress1;
	}

	public void setCustomerAddress1(String customerAddress1) {

		this.customerAddress1 = customerAddress1;
	}

	@Column(name = "customerAddress2")
	public String getCustomerAddress2() {

		return this.customerAddress2;
	}

	public void setCustomerAddress2(String customerAddress2) {

		this.customerAddress2 = customerAddress2;
	}

	@Column(name = "city", length = 100)
	public String getCity() {

		return this.city;
	}

	public void setCity(String city) {

		this.city = city;
	}

	@Column(name = "state", length = 100)
	public String getState() {

		return this.state;
	}

	public void setState(String state) {

		this.state = state;
	}

	@Column(name = "Country", length = 100)
	public String getCountry() {

		return this.country;
	}

	public void setCountry(String country) {

		this.country = country;
	}

	@Column(name = "pincode", length = 20)
	public String getPincode() {

		return this.pincode;
	}

	public void setPincode(String pincode) {

		this.pincode = pincode;
	}

	@Column(name = "type", length = 100)
	public String getType() {

		return this.type;
	}

	public void setType(String type) {

		this.type = type;
	}

	@Column(name = "category", length = 100)
	public String getCategory() {

		return this.category;
	}

	public void setCategory(String category) {

		this.category = category;
	}

	@Column(name = "website", length = 100)
	public String getWebsite() {

		return this.website;
	}

	public void setWebsite(String website) {

		this.website = website;
	}

	@Column(name = "fax", length = 100)
	public String getFax() {

		return this.fax;
	}

	public void setFax(String fax) {

		this.fax = fax;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {

		return this.email;
	}

	public void setEmail(String email) {

		this.email = email;
	}

	@Column(name = "sap_code", length = 45)
	public String getSapCode() {

		return this.sap_code;
	}

	public void setSapCode(String sap_code) {

		this.sap_code = sap_code;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

}
