
package com.velotech.fanselection.models;
// Generated Aug 13, 2019 12:37:29 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl23OfferStatusHistory generated by hbm2java
 */
@Entity
@Table(name = "tbl_23_offerStatusHistory")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl23OfferStatusHistory implements java.io.Serializable {

	private int id;

	private Tbl23OfferRev tbl23OfferRev;

	private String status;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl23OfferStatusHistory() {
	}

	public Tbl23OfferStatusHistory(int id, Tbl23OfferRev tbl23OfferRev, String status) {
		this.id = id;
		this.tbl23OfferRev = tbl23OfferRev;
		this.status = status;
	}

	public Tbl23OfferStatusHistory(int id, Tbl23OfferRev tbl23OfferRev, String status, String createdBy, Date createdDate, String modifiedBy,
			Date modifiedDate, String company) {
		this.id = id;
		this.tbl23OfferRev = tbl23OfferRev;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.company = company;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "offerRevId", nullable = false)
	public Tbl23OfferRev getTbl23OfferRev() {

		return this.tbl23OfferRev;
	}

	public void setTbl23OfferRev(Tbl23OfferRev tbl23OfferRev) {

		this.tbl23OfferRev = tbl23OfferRev;
	}

	@Column(name = "status", nullable = false, length = 50)
	public String getStatus() {

		return this.status;
	}

	public void setStatus(String status) {

		this.status = status;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

}
