
package com.velotech.fanselection.models;
// Generated May 29, 2019 3:23:32 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl28SelectedPumpBom generated by hbm2java
 */
@Entity
@Table(name = "tbl_28_selected_fan_bom")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl28SelectedFanBom implements java.io.Serializable {

	private int id;

	private Tbl26OfferFan tbl26OfferFan;

	private Tbl01ProductTypeMaster tbl01ProductTypeMaster;

	private String itemNo;

	private Integer itemId;

	private String description;

	private Double qty;

	private String qtyUom;

	private String materialDescription;

	private String articleNo;

	private Boolean reportSummary;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl28SelectedFanBom() {
	}

	public Tbl28SelectedFanBom(Tbl26OfferFan tbl26OfferFan, String itemNo, Integer itemId, String description,
			Double qty, String qtyUom, String materialDescription, String articleNo, Boolean reportSummary,
			String createdBy, Date createdDate, String modifiedBy, Date modifiedDate, String company) {
		this.tbl26OfferFan = tbl26OfferFan;
		this.itemNo = itemNo;
		this.itemId = itemId;
		this.description = description;
		this.qty = qty;
		this.qtyUom = qtyUom;
		this.materialDescription = materialDescription;
		this.articleNo = articleNo;
		this.reportSummary = reportSummary;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.company = company;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "offerFanId", nullable = false)
	public Tbl26OfferFan getTbl26OfferFan() {

		return this.tbl26OfferFan;
	}

	public void setTbl26OfferFan(Tbl26OfferFan tbl26OfferFan) {

		this.tbl26OfferFan = tbl26OfferFan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productTypeId")
	public Tbl01ProductTypeMaster getTbl01ProductTypeMaster() {

		return this.tbl01ProductTypeMaster;
	}

	public void setTbl01ProductTypeMaster(Tbl01ProductTypeMaster tbl01ProductTypeMaster) {

		this.tbl01ProductTypeMaster = tbl01ProductTypeMaster;
	}

	@Column(name = "itemNo", length = 50)
	public String getItemNo() {

		return this.itemNo;
	}

	public void setItemNo(String itemNo) {

		this.itemNo = itemNo;
	}

	@Column(name = "item_id")
	public Integer getItemId() {

		return this.itemId;
	}

	public void setItemId(Integer itemId) {

		this.itemId = itemId;
	}

	@Column(name = "description")
	public String getDescription() {

		return this.description;
	}

	public void setDescription(String description) {

		this.description = description;
	}

	@Column(name = "qty", precision = 18)
	public Double getQty() {

		return this.qty;
	}

	public void setQty(Double qty) {

		this.qty = qty;
	}

	@Column(name = "qtyUOM", length = 50)
	public String getQtyUom() {

		return this.qtyUom;
	}

	public void setQtyUom(String qtyUom) {

		this.qtyUom = qtyUom;
	}

	@Column(name = "material_description")
	public String getMaterialDescription() {

		return this.materialDescription;
	}

	public void setMaterialDescription(String materialDescription) {

		this.materialDescription = materialDescription;
	}

	@Column(name = "articleNo", length = 50)
	public String getArticleNo() {

		return this.articleNo;
	}

	public void setArticleNo(String articleNo) {

		this.articleNo = articleNo;
	}

	@Column(name = "reportSummary")
	public Boolean getReportSummary() {

		return this.reportSummary;
	}

	public void setReportSummary(Boolean reportSummary) {

		this.reportSummary = reportSummary;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

}
