
package com.velotech.fanselection.models;
// Generated May 29, 2019 3:23:32 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.ParamDef;
import org.hibernate.annotations.Parameter;

/**
 * Tbl28SelectedPrimemover generated by hbm2java
 */
@Entity
@Table(name = "tbl_28_selectedPrimemover")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl28SelectedPrimemover implements java.io.Serializable {

	private int id;

	private Tbl26OfferFan tbl26OfferFan;

	private Tbl40OfferDocument tbl40OfferDocument;

	private Double eff;

	private Integer pole;

	private String series;

	private String frameSize;

	private String frameSizeDim;

	private String moc;

	private String terminalBoxLocation;

	private Double power;

	private Double speed;

	private Integer primemoverId;

	private Integer frameMasterId;

	private String modelName;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl28SelectedPrimemover() {
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "tbl26OfferFan"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Tbl26OfferFan getTbl26OfferFan() {

		return this.tbl26OfferFan;
	}

	public void setTbl26OfferFan(Tbl26OfferFan tbl26OfferFan) {

		this.tbl26OfferFan = tbl26OfferFan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "datasheet")
	public Tbl40OfferDocument getTbl40OfferDocument() {

		return this.tbl40OfferDocument;
	}

	public void setTbl40OfferDocument(Tbl40OfferDocument tbl40OfferDocument) {

		this.tbl40OfferDocument = tbl40OfferDocument;
	}

	@Column(name = "eff", precision = 18, scale = 5)
	public Double getEff() {

		return this.eff;
	}

	public void setEff(Double eff) {

		this.eff = eff;
	}

	@Column(name = "pole")
	public Integer getPole() {

		return this.pole;
	}

	public void setPole(Integer pole) {

		this.pole = pole;
	}

	@Column(name = "series", length = 50)
	public String getSeries() {

		return this.series;
	}

	public void setSeries(String series) {

		this.series = series;
	}

	@Column(name = "frameSize", length = 50)
	public String getFrameSize() {

		return this.frameSize;
	}

	public void setFrameSize(String frameSize) {

		this.frameSize = frameSize;
	}

	@Column(name = "frameSizeDim", length = 50)
	public String getFrameSizeDim() {

		return this.frameSizeDim;
	}

	public void setFrameSizeDim(String frameSizeDim) {

		this.frameSizeDim = frameSizeDim;
	}

	@Column(name = "moc", length = 50)
	public String getMoc() {

		return this.moc;
	}

	public void setMoc(String moc) {

		this.moc = moc;
	}

	@Column(name = "terminalBoxLocation", length = 50)
	public String getTerminalBoxLocation() {

		return this.terminalBoxLocation;
	}

	public void setTerminalBoxLocation(String terminalBoxLocation) {

		this.terminalBoxLocation = terminalBoxLocation;
	}

	@Column(name = "power", precision = 18)
	public Double getPower() {

		return this.power;
	}

	public void setPower(Double power) {

		this.power = power;
	}

	@Column(name = "speed", precision = 18)
	public Double getSpeed() {

		return this.speed;
	}

	public void setSpeed(Double speed) {

		this.speed = speed;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@Column(name = "primemoverId")
	public Integer getPrimemoverId() {

		return this.primemoverId;
	}

	public void setPrimemoverId(Integer primemoverId) {

		this.primemoverId = primemoverId;
	}

	@Column(name = "frameMaster_id")
	public Integer getFrameMasterId() {

		return this.frameMasterId;
	}

	public void setFrameMasterId(Integer frameMasterId) {

		this.frameMasterId = frameMasterId;
	}

	@Column(name = "modelName", length = 255)
	public String getModelName() {

		return modelName;
	}

	public void setModelName(String modelName) {

		this.modelName = modelName;
	}

}
