
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl28OfferPumpSpecification generated by hbm2java
 */
@Entity
@Table(name = "tbl_28_offerFan_specification")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl28OfferFanSpecification implements java.io.Serializable {

	private int id;

	private Tbl26OfferFan tbl26OfferFan;

	private String parameter;

	private String value;

	private Boolean isActive;

	private Integer sequence;

	private Boolean showInQuotation;

	private Boolean showInDataSheet;

	private String groupColumn;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl28OfferFanSpecification() {
	}

	public Tbl28OfferFanSpecification(int id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "offerFanId")
	public Tbl26OfferFan getTbl26OfferFan() {

		return this.tbl26OfferFan;
	}

	public void setTbl26OfferFan(Tbl26OfferFan tbl26OfferFan) {

		this.tbl26OfferFan = tbl26OfferFan;
	}

	@Column(name = "parameter", length = 50)
	public String getParameter() {

		return this.parameter;
	}

	public void setParameter(String parameter) {

		this.parameter = parameter;
	}

	@Column(name = "value", length = 50)
	public String getValue() {

		return this.value;
	}

	public void setValue(String value) {

		this.value = value;
	}

	@Column(name = "isActive")
	public Boolean getIsActive() {

		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {

		this.isActive = isActive;
	}

	@Column(name = "sequence")
	public Integer getSequence() {

		return this.sequence;
	}

	public void setSequence(Integer sequence) {

		this.sequence = sequence;
	}

	@Column(name = "showInQuotation")
	public Boolean getShowInQuotation() {

		return this.showInQuotation;
	}

	public void setShowInQuotation(Boolean showInQuotation) {

		this.showInQuotation = showInQuotation;
	}

	@Column(name = "showInDataSheet")
	public Boolean getShowInDataSheet() {

		return this.showInDataSheet;
	}

	public void setShowInDataSheet(Boolean showInDataSheet) {

		this.showInDataSheet = showInDataSheet;
	}

	@Column(name = "groupColumn")
	public String getGroupColumn() {

		return this.groupColumn;
	}

	public void setGroupColumn(String groupColumn) {

		this.groupColumn = groupColumn;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

}
