
package com.velotech.fanselection.models;
// Generated 14 Jan, 2023 10:43:07 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.ParamDef;
import org.hibernate.annotations.Parameter;

/**
 * Tbl28SelectedPumpJsonValue generated by hbm2java
 */
@Entity
@Table(name = "tbl_28_selected_fan_JsonValue")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl28SelectedFanJsonValue implements java.io.Serializable {

	private int id;

	private Tbl26OfferFan tbl26OfferFan;

	private String jsonText;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl28SelectedFanJsonValue() {
	}

	public Tbl28SelectedFanJsonValue( Tbl26OfferFan tbl26OfferFan) {
		this.tbl26OfferFan = tbl26OfferFan;
	}

	public Tbl28SelectedFanJsonValue( Tbl26OfferFan tbl26OfferFan, String jsonText, String createdBy, Date createdDate,
			String modifiedBy, Date modifiedDate, String company) {
		this.tbl26OfferFan = tbl26OfferFan;
		this.jsonText = jsonText;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.company = company;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "tbl26OfferFan"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Tbl26OfferFan getTbl26OfferFan() {

		return this.tbl26OfferFan;
	}

	public void setTbl26OfferFan(Tbl26OfferFan tbl26OfferFan) {

		this.tbl26OfferFan = tbl26OfferFan;
	}

	@Column(name = "jsonText"/*, columnDefinition = "TEXT"*/)
	public String getJsonText() {

		return this.jsonText;
	}

	public void setJsonText(String jsonText) {

		this.jsonText = jsonText;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@Override
	public String toString() {
		return "Tbl28SelectedFanJsonValue [id=" + id + ", tbl26OfferFan=" + tbl26OfferFan.getId() + ", jsonText=" + jsonText
				+ ", createdBy=" + createdBy + ", createdDate=" + createdDate + ", modifiedBy=" + modifiedBy
				+ ", modifiedDate=" + modifiedDate + ", company=" + company + "]";
	}

}
