
package com.velotech.fanselection.models;
// Generated May 29, 2019 3:23:32 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.ParamDef;
import org.hibernate.annotations.Parameter;

import com.google.gson.annotations.Expose;

/**
 * Tbl28SelectedPump generated by hbm2java
 */
@Entity
@Table(name = "tbl_28_selected_fan")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl28SelectedFan implements java.io.Serializable {

	@Expose
	private int id;

	private Tbl26OfferFan tbl26OfferFan;

	@Expose
	private String fanModel;

	@Expose
	private String series;

	@Expose
	private String performanceCurveNo;

	@Expose
	private String rotation;

	@Expose
	private String mocStd;

	private Integer barefanGaId;

	private Integer fansetGaId;

	private Integer csdId;

	private Integer variantId;

	@Expose
	private String displayFanModelName;

	private String fanSetArticleNo;

	private Double dpFlow;

	private Double dpPressure;
	
	private Integer vaneAngle;
	
	private Integer fanModelId;

	private Integer speed;

	private Double dpPower;

	private Double dpEff;
	
	private Double velocity;

	private String pumpTypeUuid;

	private String pumpModelUuid;

	private String primeMoverUuid;

	private String motorTypeUuid;

	private String selectedFanJson;
	
	//private Integer primemoverId;
	

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl28SelectedFan() {

	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "tbl26OfferFan"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Tbl26OfferFan getTbl26OfferFan() {

		return this.tbl26OfferFan;
	}

	public void setTbl26OfferFan(Tbl26OfferFan tbl26OfferFan) {

		this.tbl26OfferFan = tbl26OfferFan;
	}

	@Column(name = "fanModel")
	public String getFanModel() {

		return this.fanModel;
	}

	public void setFanModel(String fanModel) {

		this.fanModel = fanModel;
	}
	

	@Column(name = "series", length = 50)
	public String getSeries() {

		return this.series;
	}

	public void setSeries(String series) {

		this.series = series;
	}

	@Column(name = "performanceCurveNo")
	public String getPerformanceCurveNo() {

		return this.performanceCurveNo;
	}

	public void setPerformanceCurveNo(String performanceCurveNo) {

		this.performanceCurveNo = performanceCurveNo;
	}

	@Column(name = "rotation")
	public String getRotation() {

		return this.rotation;
	}

	public void setRotation(String rotation) {

		this.rotation = rotation;
	}

	@Column(name = "mocStd", length = 50)
	public String getMocStd() {

		return this.mocStd;
	}

	public void setMocStd(String mocStd) {

		this.mocStd = mocStd;
	}


	@Column(name = "barefanGaId")
	public Integer getBarefanGaId() {

		return this.barefanGaId;
	}

	public void setBarefanGaId(Integer barefanGaId) {

		this.barefanGaId = barefanGaId;
	}

	@Column(name = "fansetGaId")
	public Integer getFansetGaId() {

		return this.fansetGaId;
	}

	public void setFansetGaId(Integer fansetGaId) {

		this.fansetGaId = fansetGaId;
	}

	@Column(name = "csdId")
	public Integer getCsdId() {

		return this.csdId;
	}

	public void setCsdId(Integer csdId) {

		this.csdId = csdId;
	}

	@Column(name = "variantId")
	public Integer getVariantId() {

		return this.variantId;
	}

	public void setVariantId(Integer variantId) {

		this.variantId = variantId;
	}

	
	@Column(name = "displayFanModelName", length = 255)
	public String getDisplayFanModelName() {

		return displayFanModelName;
	}

	public void setDisplayFanModelName(String displayFanModelName) {

		this.displayFanModelName = displayFanModelName;
	}

	@Column(name = "fanSetArticleNo", length = 255)
	public String getFanSetArticleNo() {

		return fanSetArticleNo;
	}

	public void setFanSetArticleNo(String fanSetArticleNo) {

		this.fanSetArticleNo = fanSetArticleNo;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@Column(name = "dpFlow", precision = 18)
	public Double getDpFlow() {
		return dpFlow;
	}

	public void setDpFlow(Double dpFlow) {
		this.dpFlow = dpFlow;
	}

	@Column(name = "dpPressure", precision = 18)
	public Double getDpPressure() {
		return dpPressure;
	}

	public void setDpPressure(Double dpPressure) {
		this.dpPressure = dpPressure;
	}

	@Column(name = "fanModelId")
	public Integer getFanModelId() {
		return fanModelId;
	}

	public void setFanModelId(Integer fanModelId) {
		this.fanModelId = fanModelId;
	}

	@Column(name = "speed")
	public Integer getSpeed() {
		return speed;
	}

	public void setSpeed(Integer speed) {
		this.speed = speed;
	}

	@Column(name = "dpPower", precision = 18)
	public Double getDpPower() {
		return dpPower;
	}

	public void setDpPower(Double dpPower) {
		this.dpPower = dpPower;
	}

	@Column(name = "dpEff", precision = 18)
	public Double getDpEff() {
		return dpEff;
	}

	public void setDpEff(Double dpEff) {
		this.dpEff = dpEff;
	}
	
	@Column(name = "velocity", precision = 18)
	public Double getVelocity() {
		return velocity;
	}

	public void setVelocity(Double velocity) {
		this.velocity = velocity;
	}

	@Column(name = "pumpTypeUuid", length = 50)
	public String getPumpTypeUuid() {
		return pumpTypeUuid;
	}

	public void setPumpTypeUuid(String pumpTypeUuid) {
		this.pumpTypeUuid = pumpTypeUuid;
	}

	@Column(name = "pumpModelUuid", length = 50)
	public String getPumpModelUuid() {
		return pumpModelUuid;
	}

	public void setPumpModelUuid(String pumpModelUuid) {
		this.pumpModelUuid = pumpModelUuid;
	}

	@Column(name = "primeMoverUuid", length = 50)
	public String getPrimeMoverUuid() {
		return primeMoverUuid;
	}

	public void setPrimeMoverUuid(String primeMoverUuid) {
		this.primeMoverUuid = primeMoverUuid;
	}

	@Column(name = "motorTypeUuid", length = 50)
	public String getMotorTypeUuid() {
		return motorTypeUuid;
	}

	public void setMotorTypeUuid(String motorTypeUuid) {
		this.motorTypeUuid = motorTypeUuid;
	}

	@Column(name = "selectedFanJson", length = 50)
	public String getSelectedFanJson() {
		return selectedFanJson;
	}

	
	public void setSelectedFanJson(String selectedFanJson) {
		this.selectedFanJson = selectedFanJson;
	}

	@Column(name = "vaneAngle")
	public Integer getVaneAngle() {
		return vaneAngle;
	}

	public void setVaneAngle(Integer vaneAngle) {
		this.vaneAngle = vaneAngle;
	}

	

//	@Column(name = "primemoverId")
//	public Integer getPrimemoverId() {
//		return primemoverId;
//	}
//
//	public void setPrimemoverId(Integer primemoverId) {
//		this.primemoverId = primemoverId;
//	}
	
	
}
