
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl40OfferDocument generated by hbm2java
 */
@Entity
@Table(name = "tbl_40_offerDocument")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl40OfferDocument implements java.io.Serializable {

	private int id;

	private String fileName;

	private String company;

	public Tbl40OfferDocument() {
	}

	public Tbl40OfferDocument(int id) {
		this.id = id;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@Column(name = "fileName")
	public String getFileName() {

		return this.fileName;
	}

	public void setFileName(String fileName) {

		this.fileName = fileName;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

}
