
package com.velotech.fanselection.models;
// Generated May 2, 2019 11:55:51 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl58UserCompany generated by hbm2java
 */
@Entity
@Table(name = "tbl_58_userCompany")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl58UserCompany implements java.io.Serializable {

	private int id;

	private Tbl28CompanyMaster tbl28CompanyMaster;

	private Tbl52Usermaster tbl52Usermaster;

	private Boolean defaultComp;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl58UserCompany() {
	}

	public Tbl58UserCompany(int id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "companyId")
	public Tbl28CompanyMaster getTbl28CompanyMaster() {

		return this.tbl28CompanyMaster;
	}

	public void setTbl28CompanyMaster(Tbl28CompanyMaster tbl28CompanyMaster) {

		this.tbl28CompanyMaster = tbl28CompanyMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "login_id")
	public Tbl52Usermaster getTbl52Usermaster() {

		return this.tbl52Usermaster;
	}

	public void setTbl52Usermaster(Tbl52Usermaster tbl52Usermaster) {

		this.tbl52Usermaster = tbl52Usermaster;
	}

	@Column(name = "defaultComp")
	public Boolean getDefaultComp() {

		return this.defaultComp;
	}

	public void setDefaultComp(Boolean defaultComp) {

		this.defaultComp = defaultComp;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

}
