
package com.velotech.fanselection.models;
// Generated May 2, 2019 11:55:51 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl55Userrelation generated by hbm2java
 */
@Entity
@Table(name = "tbl_55_userrelation", uniqueConstraints = @UniqueConstraint(columnNames = { "login_id",
		"reporting_to" }))
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl55Userrelation implements java.io.Serializable {

	private int id;

	private Tbl52Usermaster tbl52UsermasterByLoginId;

	private Tbl52Usermaster tbl52UsermasterByReportingTo;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl55Userrelation() {
	}

	public Tbl55Userrelation(int id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "login_id", nullable = false)
	public Tbl52Usermaster getTbl52UsermasterByLoginId() {

		return this.tbl52UsermasterByLoginId;
	}

	public void setTbl52UsermasterByLoginId(Tbl52Usermaster tbl52UsermasterByLoginId) {

		this.tbl52UsermasterByLoginId = tbl52UsermasterByLoginId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reporting_to", nullable = false)
	public Tbl52Usermaster getTbl52UsermasterByReportingTo() {

		return this.tbl52UsermasterByReportingTo;
	}

	public void setTbl52UsermasterByReportingTo(Tbl52Usermaster tbl52UsermasterByReportingTo) {

		this.tbl52UsermasterByReportingTo = tbl52UsermasterByReportingTo;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

}
