
package com.velotech.fanselection.models;
// Generated May 2, 2019 11:55:51 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

import com.google.gson.annotations.Expose;

/**
 * Tbl52Usermaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_52_usermaster")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl52Usermaster implements java.io.Serializable {

	@Expose
	private String loginId;

	private Tbl50Usertype tbl50Usertype;

	private Tbl59Organisation tbl59Organisation;

	private String email;

	private String ticketno;
	@Expose
	private String userName;

	private String password;

	private Boolean isActive;

	private Boolean activeDirectoryCheck;

	private String mobileNo;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	private Boolean ipCheck;

	private String ipNumber;

	private Boolean isEmail;

	public Tbl52Usermaster() {
	}

	public Tbl52Usermaster(String loginId) {
		this.loginId = loginId;
	}

	@Id
	@Column(name = "login_id", unique = true, nullable = false, length = 100)
	public String getLoginId() {

		return this.loginId;
	}

	public void setLoginId(String loginId) {

		this.loginId = loginId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userTypeId")
	public Tbl50Usertype getTbl50Usertype() {

		return this.tbl50Usertype;
	}

	public void setTbl50Usertype(Tbl50Usertype tbl50Usertype) {

		this.tbl50Usertype = tbl50Usertype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organisationId")
	public Tbl59Organisation getTbl59Organisation() {

		return this.tbl59Organisation;
	}

	public void setTbl59Organisation(Tbl59Organisation tbl59Organisation) {

		this.tbl59Organisation = tbl59Organisation;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {

		return this.email;
	}

	public void setEmail(String email) {

		this.email = email;
	}

	@Column(name = "ticketno", nullable = false, length = 100)
	public String getTicketno() {

		return this.ticketno;
	}

	public void setTicketno(String ticketno) {

		this.ticketno = ticketno;
	}

	@Column(name = "user_name", nullable = false, length = 100)
	public String getUserName() {

		return this.userName;
	}

	public void setUserName(String userName) {

		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {

		return this.password;
	}

	public void setPassword(String password) {

		this.password = password;
	}

	@Column(name = "isActive")
	public Boolean getIsActive() {

		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {

		this.isActive = isActive;
	}

	@Column(name = "activeDirectoryCheck")
	public Boolean getActiveDirectoryCheck() {

		return this.activeDirectoryCheck;
	}

	public void setActiveDirectoryCheck(Boolean activeDirectoryCheck) {

		this.activeDirectoryCheck = activeDirectoryCheck;
	}

	@Column(name = "mobileNo", length = 15)
	public String getMobileNo() {

		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {

		this.mobileNo = mobileNo;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@Column(name = "ipCheck")
	public Boolean getIpCheck() {

		return this.ipCheck;
	}

	public void setIpCheck(Boolean ipCheck) {

		this.ipCheck = ipCheck;
	}

	@Column(name = "ipNumber", length = 50)
	public String getIpNumber() {

		return this.ipNumber;
	}

	public void setIpNumber(String ipNumber) {

		this.ipNumber = ipNumber;
	}

	@Column(name = "isEmail")
	public Boolean getIsEmail() {

		return isEmail;
	}

	public void setIsEmail(Boolean isEmail) {

		this.isEmail = isEmail;
	}

}
