
package com.velotech.fanselection.models;
// Generated 24 Oct, 2019 11:37:59 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl51UsertypeSelectiontypeMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_51_usertype_selectiontype_master")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl51UsertypeSelectiontypeMaster implements java.io.Serializable {

	private int id;

	//private Tbl00SelectiontypeMaster tbl00SelectiontypeMaster;

	private Tbl50Usertype tbl50Usertype;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl51UsertypeSelectiontypeMaster() {
	}

	public Tbl51UsertypeSelectiontypeMaster(int id) {
		this.id = id;
	}

	/*public Tbl51UsertypeSelectiontypeMaster(int id, Tbl00SelectiontypeMaster tbl00SelectiontypeMaster, Tbl50Usertype tbl50Usertype) {
		this.id = id;
		this.tbl00SelectiontypeMaster = tbl00SelectiontypeMaster;
		this.tbl50Usertype = tbl50Usertype;
	}*/

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "selectionTypeId")
	public Tbl00SelectiontypeMaster getTbl00SelectiontypeMaster() {

		return this.tbl00SelectiontypeMaster;
	}

	public void setTbl00SelectiontypeMaster(Tbl00SelectiontypeMaster tbl00SelectiontypeMaster) {

		this.tbl00SelectiontypeMaster = tbl00SelectiontypeMaster;
	}*/

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userTypeId")
	public Tbl50Usertype getTbl50Usertype() {

		return this.tbl50Usertype;
	}

	public void setTbl50Usertype(Tbl50Usertype tbl50Usertype) {

		this.tbl50Usertype = tbl50Usertype;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}
}
