
package com.velotech.fanselection.models;
// Generated 25 Jun, 2019 2:06:29 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl61ProjectSummaryQuoteReport generated by hbm2java
 */
@Entity
@Table(name = "tbl_61_projectSummaryQuoteReport")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl61ProjectSummaryQuoteReport implements java.io.Serializable {

	private int id;

	private String sessionId;

	private Integer offerFanId;

	private String parameter;

	private String value;

	private String tagNo;

	private String group1;

	private Integer sequence;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl61ProjectSummaryQuoteReport() {
	}

	public Tbl61ProjectSummaryQuoteReport(int id) {
		this.id = id;
	}

	public Tbl61ProjectSummaryQuoteReport(int id, String sessionId, Integer offerFanId, String parameter, String value, String tagNo, String group1,
			Integer sequence) {
		this.id = id;
		this.sessionId = sessionId;
		this.offerFanId = offerFanId;
		this.parameter = parameter;
		this.value = value;
		this.tagNo = tagNo;
		this.group1 = group1;
		this.sequence = sequence;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@Column(name = "sessionId")
	public String getSessionId() {

		return this.sessionId;
	}

	public void setSessionId(String sessionId) {

		this.sessionId = sessionId;
	}

	@Column(name = "offerFanId")
	public Integer getOfferFanId() {
		return offerFanId;
	}

	public void setOfferFanId(Integer offerFanId) {
		this.offerFanId = offerFanId;
	}
	
	
	
	
	

	@Column(name = "parameter")
	public String getParameter() {

		return this.parameter;
	}


	public void setParameter(String parameter) {

		this.parameter = parameter;
	}

	@Column(name = "value")
	public String getValue() {

		return this.value;
	}

	public void setValue(String value) {

		this.value = value;
	}

	@Column(name = "tagNo", length = 50)
	public String getTagNo() {

		return this.tagNo;
	}

	public void setTagNo(String tagNo) {

		this.tagNo = tagNo;
	}

	@Column(name = "group1")
	public String getGroup1() {

		return this.group1;
	}

	public void setGroup1(String group1) {

		this.group1 = group1;
	}

	@Column(name = "sequence")
	public Integer getSequence() {

		return this.sequence;
	}

	public void setSequence(Integer sequence) {

		this.sequence = sequence;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

}
