
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl80TemplateMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_80_templateMaster", uniqueConstraints = @UniqueConstraint(columnNames = { "fileName", "company" }))
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl80TemplateMaster implements java.io.Serializable {

	private int id;

	private String fileName;

	private String layout;

	private String layersList;

	private String description;

	private String name;

	private String attachedFile;

	private String parameterList;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	private String documentIds;

	private Tbl90DocumentMaster tbl90DocumentMaster;

	public Tbl80TemplateMaster() {
	}

	public Tbl80TemplateMaster(int id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@Column(name = "fileName", length = 50)
	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "layout", length = 50)
	public String getLayout() {

		return this.layout;
	}

	public void setLayout(String layout) {

		this.layout = layout;
	}

	@Column(name = "layersList", columnDefinition = "TEXT")
	public String getLayersList() {

		return this.layersList;
	}

	public void setLayersList(String layersList) {

		this.layersList = layersList;
	}

	@Column(name = "description", columnDefinition = "TEXT")
	public String getDescription() {

		return this.description;
	}

	public void setDescription(String description) {

		this.description = description;
	}

	@Column(name = "name", columnDefinition = "TEXT")
	public String getName() {

		return this.name;
	}

	public void setName(String name) {

		this.name = name;
	}

	@Column(name = "attachedFile")
	public String getAttachedFile() {

		return this.attachedFile;
	}

	public void setAttachedFile(String attachedFile) {

		this.attachedFile = attachedFile;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@Column(name = "parameterList", columnDefinition = "TEXT")
	public String getParameterList() {

		return parameterList;
	}

	public void setParameterList(String parameterList) {

		this.parameterList = parameterList;
	}

	@Column(name = "documentIds", columnDefinition = "TEXT")
	public String getDocumentIds() {
		return documentIds;
	}

	public void setDocumentIds(String documentIds) {
		this.documentIds = documentIds;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "documentId")

	public Tbl90DocumentMaster getTbl90DocumentMaster() {
		return tbl90DocumentMaster;
	}

	public void setTbl90DocumentMaster(Tbl90DocumentMaster tbl90DocumentMaster) {
		this.tbl90DocumentMaster = tbl90DocumentMaster;
	}

}
