
package com.velotech.fanselection.models;
// Generated Aug 21, 2021 12:38:16 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl90EmailLog generated by hbm2java
 */
@Entity
@Table(name = "tbl_90_emailLog")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl90EmailLog implements java.io.Serializable {

	private int id;

	private String emailTo;

	private String emailFrom;

	private String cc;

	private String bcc;

	private String subject;

	private String emailbody;

	private Boolean emailStatus;

	private String offerRev;

	private String offerNo;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl90EmailLog() {
	}

	public Tbl90EmailLog(int id) {
		this.id = id;
	}

	public Tbl90EmailLog(int id, String emailTo, String emailFrom, String cc, String subject, String emailbody, Boolean emailStatus, String company) {
		this.id = id;
		this.emailTo = emailTo;
		this.emailFrom = emailFrom;
		this.cc = cc;
		this.subject = subject;
		this.emailbody = emailbody;
		this.emailStatus = emailStatus;
		this.company = company;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@Column(name = "emailTo")
	public String getEmailTo() {

		return this.emailTo;
	}

	public void setEmailTo(String emailTo) {

		this.emailTo = emailTo;
	}

	@Column(name = "emailFrom", length = 100)
	public String getEmailFrom() {

		return this.emailFrom;
	}

	public void setEmailFrom(String emailFrom) {

		this.emailFrom = emailFrom;
	}

	@Column(name = "cc")
	public String getCc() {

		return this.cc;
	}

	public void setCc(String cc) {

		this.cc = cc;
	}

	@Column(name = "bcc")
	public String getBcc() {

		return bcc;
	}

	public void setBcc(String bcc) {

		this.bcc = bcc;
	}

	@Column(name = "subject")
	public String getSubject() {

		return this.subject;
	}

	public void setSubject(String subject) {

		this.subject = subject;
	}

	@Column(name = "emailStatus")
	public Boolean getEmailStatus() {

		return this.emailStatus;
	}

	public void setEmailStatus(Boolean emailStatus) {

		this.emailStatus = emailStatus;
	}

	@Column(name = "offerRev", length = 5)
	public String getOfferRev() {

		return offerRev;
	}

	public void setOfferRev(String offerRev) {

		this.offerRev = offerRev;
	}

	@Column(name = "offerNo", length = 50)
	public String getOfferNo() {

		return offerNo;
	}

	public void setOfferNo(String offerNo) {

		this.offerNo = offerNo;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@Column(name = "emailbody")
	public String getEmailbody() {

		return emailbody;
	}

	public void setEmailbody(String emailbody) {

		this.emailbody = emailbody;
	}

}
