
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

import com.google.gson.annotations.Expose;

/**
 * Tbl23OfferRev generated by hbm2java
 */
@Entity
@Table(name = "tbl_23_offerRev", uniqueConstraints = @UniqueConstraint(columnNames = { "offerNoId", "rev", "company" }))
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl23OfferRev implements java.io.Serializable {

	private int id;
	@Expose
	private Tbl23OfferMaster tbl23OfferMaster;
	@Expose
	private Tbl25CustomerMaster tbl25CustomerMaster;
	@Expose
	private Tbl28CompanyMaster tbl28CompanyMaster;

	private Tbl40OfferDocument tbl40OfferDocumentByClientLogo;

	private Tbl40OfferDocument tbl40OfferDocumentByLogo1;

	private Tbl40OfferDocument tbl40OfferDocumentByLogo;

	private Tbl52Usermaster tbl52UsermasterBySalesPerson;
	@Expose
	private Tbl52Usermaster tbl52UsermasterByLoginId;

	private Tbl80SegmentMaster tbl80SegmentMaster;

	@Expose
	private String rev;
	@Expose
	private String status;
	@Expose
	private Boolean isOrder;
	@Expose
	private String orderNo;
	@Expose
	private Double orderPrice;
	@Expose
	private Date offerdate;
	@Expose
	private String consultant;
	@Expose
	private String endUser;
	@Expose
	private String project;
	@Expose
	private String contractor;
	@Expose
	private String suppliedBy;
	@Expose
	private String currency;
	@Expose
	private String pricingType;
	@Expose
	private String pricingLocation;
	@Expose
	private String reference;
	@Expose
	private String enquiryDetails;
	@Expose
	private Date enquiryDate;
	@Expose
	private String subject;
	@Expose
	private Boolean activetFlag;
	@Expose
	private Boolean standardOffer;

	private Boolean tempOffer;

	private Boolean showPriceBreakUp;

	private Boolean showPrice;

	private Boolean showTagPrice;

	private Boolean showDiscount;

	private Boolean showCoveringLetter;

	private String coverLetterContent;

	private Double lineTotal;

	private Double addonTotal;

	private Double factorTotal;

	private Double offerTotal;

	private Date tenderDate;

	private Date tenderDueDate;

	private Date priceReqDate;

	private String branchHeadOffice;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl23OfferRev() {

	}

	public Tbl23OfferRev(int id, String rev) {

		this.id = id;
		this.rev = rev;
	}

	public Tbl23OfferRev(Integer offerRevId) {

		this.id = offerRevId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "offerNoId")
	public Tbl23OfferMaster getTbl23OfferMaster() {

		return this.tbl23OfferMaster;
	}

	public void setTbl23OfferMaster(Tbl23OfferMaster tbl23OfferMaster) {

		this.tbl23OfferMaster = tbl23OfferMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	public Tbl25CustomerMaster getTbl25CustomerMaster() {

		return this.tbl25CustomerMaster;
	}

	public void setTbl25CustomerMaster(Tbl25CustomerMaster tbl25CustomerMaster) {

		this.tbl25CustomerMaster = tbl25CustomerMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "companyId")
	public Tbl28CompanyMaster getTbl28CompanyMaster() {

		return this.tbl28CompanyMaster;
	}

	public void setTbl28CompanyMaster(Tbl28CompanyMaster tbl28CompanyMaster) {

		this.tbl28CompanyMaster = tbl28CompanyMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clientLogo")
	public Tbl40OfferDocument getTbl40OfferDocumentByClientLogo() {

		return this.tbl40OfferDocumentByClientLogo;
	}

	public void setTbl40OfferDocumentByClientLogo(Tbl40OfferDocument tbl40OfferDocumentByClientLogo) {

		this.tbl40OfferDocumentByClientLogo = tbl40OfferDocumentByClientLogo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "logo1")
	public Tbl40OfferDocument getTbl40OfferDocumentByLogo1() {

		return this.tbl40OfferDocumentByLogo1;
	}

	public void setTbl40OfferDocumentByLogo1(Tbl40OfferDocument tbl40OfferDocumentByLogo1) {

		this.tbl40OfferDocumentByLogo1 = tbl40OfferDocumentByLogo1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "logo")
	public Tbl40OfferDocument getTbl40OfferDocumentByLogo() {

		return this.tbl40OfferDocumentByLogo;
	}

	public void setTbl40OfferDocumentByLogo(Tbl40OfferDocument tbl40OfferDocumentByLogo) {

		this.tbl40OfferDocumentByLogo = tbl40OfferDocumentByLogo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "salesPerson")
	public Tbl52Usermaster getTbl52UsermasterBySalesPerson() {

		return this.tbl52UsermasterBySalesPerson;
	}

	public void setTbl52UsermasterBySalesPerson(Tbl52Usermaster tbl52UsermasterBySalesPerson) {

		this.tbl52UsermasterBySalesPerson = tbl52UsermasterBySalesPerson;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "login_id")
	public Tbl52Usermaster getTbl52UsermasterByLoginId() {

		return this.tbl52UsermasterByLoginId;
	}

	public void setTbl52UsermasterByLoginId(Tbl52Usermaster tbl52UsermasterByLoginId) {

		this.tbl52UsermasterByLoginId = tbl52UsermasterByLoginId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "segmentId")
	public Tbl80SegmentMaster getTbl80SegmentMaster() {

		return this.tbl80SegmentMaster;
	}

	public void setTbl80SegmentMaster(Tbl80SegmentMaster tbl80SegmentMaster) {

		this.tbl80SegmentMaster = tbl80SegmentMaster;
	}

	@Column(name = "rev", nullable = false, length = 5)
	public String getRev() {

		return this.rev;
	}

	public void setRev(String rev) {

		this.rev = rev;
	}

	@Column(name = "isOrder")
	public Boolean getIsOrder() {

		return this.isOrder;
	}

	public void setIsOrder(Boolean isOrder) {

		this.isOrder = isOrder;
	}

	@Column(name = "orderNo", length = 50)
	public String getOrderNo() {

		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {

		this.orderNo = orderNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "offerdate", length = 10)
	public Date getOfferdate() {

		return this.offerdate;
	}

	public void setOfferdate(Date offerdate) {

		this.offerdate = offerdate;
	}

	@Column(name = "status")
	public String getStatus() {

		return this.status;
	}

	public void setStatus(String status) {

		this.status = status;
	}

	@Column(name = "orderPrice", precision = 18)
	public Double getOrderPrice() {

		return this.orderPrice;
	}

	public void setOrderPrice(Double orderPrice) {

		this.orderPrice = orderPrice;
	}

	@Column(name = "consultant")
	public String getConsultant() {

		return this.consultant;
	}

	public void setConsultant(String consultant) {

		this.consultant = consultant;
	}

	@Column(name = "endUser")
	public String getEndUser() {

		return this.endUser;
	}

	public void setEndUser(String endUser) {

		this.endUser = endUser;
	}

	@Column(name = "project")
	public String getProject() {

		return this.project;
	}

	public void setProject(String project) {

		this.project = project;
	}

	@Column(name = "contractor")
	public String getContractor() {

		return this.contractor;
	}

	public void setContractor(String contractor) {

		this.contractor = contractor;
	}

	@Column(name = "suppliedBy")
	public String getSuppliedBy() {

		return this.suppliedBy;
	}

	public void setSuppliedBy(String suppliedBy) {

		this.suppliedBy = suppliedBy;
	}

	@Column(name = "currency", length = 10)
	public String getCurrency() {

		return this.currency;
	}

	public void setCurrency(String currency) {

		this.currency = currency;
	}

	@Column(name = "pricingType", length = 50)
	public String getPricingType() {

		return this.pricingType;
	}

	public void setPricingType(String pricingType) {

		this.pricingType = pricingType;
	}

	@Column(name = "pricingLocation", length = 50)
	public String getPricingLocation() {

		return this.pricingLocation;
	}

	public void setPricingLocation(String pricingLocation) {

		this.pricingLocation = pricingLocation;
	}

	@Column(name = "reference")
	public String getReference() {

		return this.reference;
	}

	public void setReference(String reference) {

		this.reference = reference;
	}

	@Column(name = "enquiryDetails")
	public String getEnquiryDetails() {

		return this.enquiryDetails;
	}

	public void setEnquiryDetails(String enquiryDetails) {

		this.enquiryDetails = enquiryDetails;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enquiryDate", length = 10)
	public Date getEnquiryDate() {

		return this.enquiryDate;
	}

	public void setEnquiryDate(Date enquiryDate) {

		this.enquiryDate = enquiryDate;
	}

	@Column(name = "subject", columnDefinition = "TEXT")
	public String getSubject() {

		return this.subject;
	}

	public void setSubject(String subject) {

		this.subject = subject;
	}

	@Column(name = "activetFlag")
	public Boolean getActivetFlag() {

		return this.activetFlag;
	}

	public void setActivetFlag(Boolean activetFlag) {

		this.activetFlag = activetFlag;
	}

	@Column(name = "standardOffer")
	public Boolean getStandardOffer() {

		return this.standardOffer;
	}

	public void setStandardOffer(Boolean standardOffer) {

		this.standardOffer = standardOffer;
	}

	@Column(name = "tempOffer")
	public Boolean getTempOffer() {

		return this.tempOffer;
	}

	public void setTempOffer(Boolean tempOffer) {

		this.tempOffer = tempOffer;
	}

	@Column(name = "showPriceBreakUp")
	public Boolean getShowPriceBreakUp() {

		return this.showPriceBreakUp;
	}

	public void setShowPriceBreakUp(Boolean showPriceBreakUp) {

		this.showPriceBreakUp = showPriceBreakUp;
	}

	@Column(name = "showPrice")
	public Boolean getShowPrice() {

		return this.showPrice;
	}

	public void setShowPrice(Boolean showPrice) {

		this.showPrice = showPrice;
	}

	@Column(name = "showTagPrice")
	public Boolean getShowTagPrice() {

		return this.showTagPrice;
	}

	public void setShowTagPrice(Boolean showTagPrice) {

		this.showTagPrice = showTagPrice;
	}

	@Column(name = "showDiscount")
	public Boolean getShowDiscount() {

		return this.showDiscount;
	}

	public void setShowDiscount(Boolean showDiscount) {

		this.showDiscount = showDiscount;
	}

	@Column(name = "showCoveringLetter")
	public Boolean getShowCoveringLetter() {

		return this.showCoveringLetter;
	}

	public void setShowCoveringLetter(Boolean showCoveringLetter) {

		this.showCoveringLetter = showCoveringLetter;
	}

	@Column(name = "coverLetterContent", columnDefinition = "TEXT")
	public String getCoverLetterContent() {

		return this.coverLetterContent;
	}

	public void setCoverLetterContent(String coverLetterContent) {

		this.coverLetterContent = coverLetterContent;
	}

	@Column(name = "lineTotal", precision = 18)
	public Double getLineTotal() {

		return this.lineTotal;
	}

	public void setLineTotal(Double lineTotal) {

		this.lineTotal = lineTotal;
	}

	@Column(name = "addonTotal", precision = 18)
	public Double getAddonTotal() {

		return this.addonTotal;
	}

	public void setAddonTotal(Double addonTotal) {

		this.addonTotal = addonTotal;
	}

	@Column(name = "factorTotal", precision = 18)
	public Double getFactorTotal() {

		return this.factorTotal;
	}

	public void setFactorTotal(Double factorTotal) {

		this.factorTotal = factorTotal;
	}

	@Column(name = "offerTotal", precision = 18)
	public Double getOfferTotal() {

		return this.offerTotal;
	}

	public void setOfferTotal(Double offerTotal) {

		this.offerTotal = offerTotal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tenderDate", length = 10)
	public Date getTenderDate() {

		return this.tenderDate;
	}

	public void setTenderDate(Date tenderDate) {

		this.tenderDate = tenderDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tenderDueDate", length = 10)

	public Date getTenderDueDate() {

		return tenderDueDate;
	}

	public void setTenderDueDate(Date tenderDueDate) {

		this.tenderDueDate = tenderDueDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "priceReqDate", length = 10)
	public Date getPriceReqDate() {

		return this.priceReqDate;
	}

	public void setPriceReqDate(Date priceReqDate) {

		this.priceReqDate = priceReqDate;
	}

	@Column(name = "branchHeadOffice")
	public String getBranchHeadOffice() {

		return this.branchHeadOffice;
	}

	public void setBranchHeadOffice(String branchHeadOffice) {

		this.branchHeadOffice = branchHeadOffice;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}
}
