
package com.velotech.fanselection.models;
// Generated Jul 18, 2019 12:12:48 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Tbl00ClientPreferences generated by hbm2java
 */
@Entity
@Table(name = "tbl_00_client_preferences")
public class Tbl00ClientPreferences implements java.io.Serializable {

	private String clientId;

	private Tbl00ClientMaster tbl00ClientMaster;

	private String currency;

	private String graphColor;

	private String offerPreffix;

	private String orderPreffix;

	public Tbl00ClientPreferences() {
	}

	public Tbl00ClientPreferences(Tbl00ClientMaster tbl00ClientMaster) {
		this.tbl00ClientMaster = tbl00ClientMaster;
	}

	public Tbl00ClientPreferences(Tbl00ClientMaster tbl00ClientMaster, String currency, String graphColor, String offerPreffix, String orderPreffix) {
		this.tbl00ClientMaster = tbl00ClientMaster;
		this.currency = currency;
		this.graphColor = graphColor;
		this.offerPreffix = offerPreffix;
		this.orderPreffix = orderPreffix;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "tbl00ClientMaster"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "clientId", unique = true, nullable = false, length = 50)
	public String getClientId() {

		return this.clientId;
	}

	public void setClientId(String clientId) {

		this.clientId = clientId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Tbl00ClientMaster getTbl00ClientMaster() {

		return this.tbl00ClientMaster;
	}

	public void setTbl00ClientMaster(Tbl00ClientMaster tbl00ClientMaster) {

		this.tbl00ClientMaster = tbl00ClientMaster;
	}

	@Column(name = "currency", length = 50)
	public String getCurrency() {

		return this.currency;
	}

	public void setCurrency(String currency) {

		this.currency = currency;
	}

	@Column(name = "graphColor", length = 50)
	public String getGraphColor() {

		return this.graphColor;
	}

	public void setGraphColor(String graphColor) {

		this.graphColor = graphColor;
	}

	@Column(name = "offerPreffix", length = 50)
	public String getOfferPreffix() {

		return this.offerPreffix;
	}

	public void setOfferPreffix(String offerPreffix) {

		this.offerPreffix = offerPreffix;
	}

	@Column(name = "orderPreffix", length = 50)
	public String getOrderPreffix() {

		return this.orderPreffix;
	}

	public void setOrderPreffix(String orderPreffix) {

		this.orderPreffix = orderPreffix;
	}

}
