
package com.velotech.fanselection.models;
// Generated 22 Jan, 2020 7:04:36 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl90DocumentMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_90_documentMaster")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl90DocumentMaster implements java.io.Serializable {

	private int id;

	private String fileName;

	private String location;

	private String referenceTable;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl90DocumentMaster() {
	}

	public Tbl90DocumentMaster(int id) {
		this.id = id;
	}

	public Tbl90DocumentMaster(int id, String fileName, String location, String referenceTable, String createdBy, Date createdDate, String modifiedBy,
			Date modifiedDate, String company) {
		this.id = id;
		this.fileName = fileName;
		this.location = location;
		this.referenceTable = referenceTable;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.company = company;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@Column(name = "fileName")
	public String getFileName() {

		return this.fileName;
	}

	public void setFileName(String fileName) {

		this.fileName = fileName;
	}

	@Column(name = "location")
	public String getLocation() {

		return this.location;
	}

	public void setLocation(String location) {

		this.location = location;
	}

	@Column(name = "referenceTable", length = 50)
	public String getReferenceTable() {

		return this.referenceTable;
	}

	public void setReferenceTable(String referenceTable) {

		this.referenceTable = referenceTable;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	
}
