
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl14FrameMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_14_frameMaster", uniqueConstraints = @UniqueConstraint(columnNames = { "frameSize",
		"pole", "company" }))
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl14FrameMaster implements java.io.Serializable {

	private int id;

	private String frameSize;

	private Integer pole;

	private Double shaftDia;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;
	
	private String uuid;

	public Tbl14FrameMaster() {
	}

	public Tbl14FrameMaster(int id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@Column(name = "frameSize", length = 50)
	public String getFrameSize() {

		return this.frameSize;
	}

	public void setFrameSize(String frameSize) {

		this.frameSize = frameSize;
	}

	@Column(name = "pole")
	public Integer getPole() {

		return this.pole;
	}

	public void setPole(Integer pole) {

		this.pole = pole;
	}

	@Column(name = "shaftDia", precision = 18, scale = 3)
	public Double getShaftDia() {

		return this.shaftDia;
	}

	public void setShaftDia(Double shaftDia) {

		this.shaftDia = shaftDia;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}
	
	
	@Column(name = "uuid", columnDefinition = "uniqueidentifier")
	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Override
	public String toString() {

		return "Tbl14FrameMaster [id=" + id + ", frameSize=" + frameSize + ", pole=" + pole + ", shaftDia=" + shaftDia + ", createdBy=" + createdBy
				+ ", createdDate=" + createdDate + ", modifiedBy=" + modifiedBy + ", modifiedDate=" + modifiedDate + ", company=" + company
				+ "]";
	}

}
