
package com.velotech.fanselection.models;
// Generated Jun 25, 2019 5:39:16 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl90XmlPerformanceDia generated by hbm2java
 */
@Entity
@Table(name = "tbl_90_xml_performance_vane")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl90XmlPerformanceVane implements java.io.Serializable {

	private String performanceVaneId;

	private Tbl90XmlModelmaster tbl90XmlModelmaster;

	// private Tbl02Modelmaster tbl02Modelmaster;

	private Integer vaneAngle;

	private Integer headDegree;

	private Integer powerDegree;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	private Set<Tbl90XmlPerformanceDataHead> tbl90XmlPerformanceDataHeads = new HashSet<Tbl90XmlPerformanceDataHead>(0);

	public Tbl90XmlPerformanceVane() {
	}

	@Id
	@Column(name = "performanceVane_id", unique = true, nullable = false, length = 200)
	public String getPerformanceVaneId() {

		return this.performanceVaneId;
	}

	public void setPerformanceVaneId(String performanceVaneId) {

		this.performanceVaneId = performanceVaneId;
	}

	/*
	 * @ManyToOne(fetch = FetchType.LAZY)
	 * 
	 * @JoinColumn(name = "fanModelId", nullable = false) public Tbl02Modelmaster
	 * getTbl02Modelmaster() {
	 * 
	 * return this.tbl02Modelmaster; }
	 * 
	 * public void setTbl02Modelmaster(Tbl02Modelmaster tbl02Modelmaster) {
	 * 
	 * this.tbl02Modelmaster = tbl02Modelmaster; }
	 */

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fanModelId", nullable = false)
	public Tbl90XmlModelmaster getTbl90XmlModelmaster() {
		return tbl90XmlModelmaster;
	}

	public void setTbl90XmlModelmaster(Tbl90XmlModelmaster tbl90XmlModelmaster) {
		this.tbl90XmlModelmaster = tbl90XmlModelmaster;
	}

	@Column(name = "vaneAngle")
	public Integer getVaneAngle() {
		return vaneAngle;
	}

	public void setVaneAngle(Integer vaneAngle) {
		this.vaneAngle = vaneAngle;
	}

	@Column(name = "headDegree")
	public Integer getHeadDegree() {

		return this.headDegree;
	}

	public void setHeadDegree(Integer headDegree) {

		this.headDegree = headDegree;
	}

	@Column(name = "powerDegree")
	public Integer getPowerDegree() {

		return this.powerDegree;
	}

	public void setPowerDegree(Integer powerDegree) {

		this.powerDegree = powerDegree;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbl90XmlPerformanceVane")
	public Set<Tbl90XmlPerformanceDataHead> getTbl90XmlPerformanceDataHeads() {

		return this.tbl90XmlPerformanceDataHeads;
	}

	public void setTbl90XmlPerformanceDataHeads(Set<Tbl90XmlPerformanceDataHead> tbl90XmlPerformanceDataHeads) {

		this.tbl90XmlPerformanceDataHeads = tbl90XmlPerformanceDataHeads;
	}

}
