
package com.velotech.fanselection.models.views;
// Generated Aug 6, 2019 4:13:18 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MisOfferId generated by hbm2java
 */
@Embeddable
public class MisOfferId implements java.io.Serializable {

	private int offerMasterId;

	private String offerNo;

	private int offerRevId;

	private String offerRev;

	private Boolean isOrder;

	private Double orderPrice;

	private Integer segmentId;

	private String segment;

	private Date offerDate;

	private Integer customerId;

	private String customerName;

	private String offerStatus;

	private String project;

	private String consultant;

	private String endUser;

	private String contractor;

	private String currency;

	private String loginId;

	private Boolean activeFlag;

	private Boolean standardOffer;

	private Double offerTotal;

	private String salesPerson;

	private String company;

	public MisOfferId() {
	}

	public MisOfferId(int offerMasterId, int offerRevId, String offerRev, String segment) {
		this.offerMasterId = offerMasterId;
		this.offerRevId = offerRevId;
		this.offerRev = offerRev;
		this.segment = segment;
	}

	public MisOfferId(int offerMasterId, String offerNo, int offerRevId, String offerRev, Boolean isOrder, Double orderPrice, Integer segmentId,
			String segment, Date offerDate, Integer customerId, String customerName, String offerStatus, String project, String consultant,
			String endUser, String contractor, String currency, String loginId, Boolean activeFlag, Boolean standardOffer, Double offerTotal,
			String salesPerson, String company) {
		this.offerMasterId = offerMasterId;
		this.offerNo = offerNo;
		this.offerRevId = offerRevId;
		this.offerRev = offerRev;
		this.isOrder = isOrder;
		this.orderPrice = orderPrice;
		this.segmentId = segmentId;
		this.segment = segment;
		this.offerDate = offerDate;
		this.customerId = customerId;
		this.customerName = customerName;
		this.offerStatus = offerStatus;
		this.project = project;
		this.consultant = consultant;
		this.endUser = endUser;
		this.contractor = contractor;
		this.currency = currency;
		this.loginId = loginId;
		this.activeFlag = activeFlag;
		this.standardOffer = standardOffer;
		this.offerTotal = offerTotal;
		this.salesPerson = salesPerson;
		this.company = company;
	}

	@Column(name = "offerMasterId", nullable = false)
	public int getOfferMasterId() {

		return this.offerMasterId;
	}

	public void setOfferMasterId(int offerMasterId) {

		this.offerMasterId = offerMasterId;
	}

	@Column(name = "offerNo", length = 50)
	public String getOfferNo() {

		return this.offerNo;
	}

	public void setOfferNo(String offerNo) {

		this.offerNo = offerNo;
	}

	@Column(name = "offerRevId", nullable = false)
	public int getOfferRevId() {

		return this.offerRevId;
	}

	public void setOfferRevId(int offerRevId) {

		this.offerRevId = offerRevId;
	}

	@Column(name = "offerRev", nullable = false, length = 5)
	public String getOfferRev() {

		return this.offerRev;
	}

	public void setOfferRev(String offerRev) {

		this.offerRev = offerRev;
	}

	@Column(name = "isOrder")
	public Boolean getIsOrder() {

		return this.isOrder;
	}

	public void setIsOrder(Boolean isOrder) {

		this.isOrder = isOrder;
	}

	@Column(name = "orderPrice", precision = 18)
	public Double getOrderPrice() {

		return this.orderPrice;
	}

	public void setOrderPrice(Double orderPrice) {

		this.orderPrice = orderPrice;
	}

	@Column(name = "segmentId")
	public Integer getSegmentId() {

		return this.segmentId;
	}

	public void setSegmentId(Integer segmentId) {

		this.segmentId = segmentId;
	}

	@Column(name = "segment", nullable = false)
	public String getSegment() {

		return this.segment;
	}

	public void setSegment(String segment) {

		this.segment = segment;
	}

	@Column(name = "offerDate", length = 10)
	public Date getOfferDate() {

		return this.offerDate;
	}

	public void setOfferDate(Date offerDate) {

		this.offerDate = offerDate;
	}

	@Column(name = "customerId")
	public Integer getCustomerId() {

		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {

		this.customerId = customerId;
	}

	@Column(name = "customerName")
	public String getCustomerName() {

		return this.customerName;
	}

	public void setCustomerName(String customerName) {

		this.customerName = customerName;
	}

	@Column(name = "offerStatus")
	public String getOfferStatus() {

		return this.offerStatus;
	}

	public void setOfferStatus(String offerStatus) {

		this.offerStatus = offerStatus;
	}

	@Column(name = "project")
	public String getProject() {

		return this.project;
	}

	public void setProject(String project) {

		this.project = project;
	}

	@Column(name = "consultant")
	public String getConsultant() {

		return this.consultant;
	}

	public void setConsultant(String consultant) {

		this.consultant = consultant;
	}

	@Column(name = "endUser")
	public String getEndUser() {

		return this.endUser;
	}

	public void setEndUser(String endUser) {

		this.endUser = endUser;
	}

	@Column(name = "contractor")
	public String getContractor() {

		return this.contractor;
	}

	public void setContractor(String contractor) {

		this.contractor = contractor;
	}

	@Column(name = "currency", length = 10)
	public String getCurrency() {

		return this.currency;
	}

	public void setCurrency(String currency) {

		this.currency = currency;
	}

	@Column(name = "loginId", length = 100)
	public String getLoginId() {

		return this.loginId;
	}

	public void setLoginId(String loginId) {

		this.loginId = loginId;
	}

	@Column(name = "activeFlag")
	public Boolean getActiveFlag() {

		return this.activeFlag;
	}

	public void setActiveFlag(Boolean activeFlag) {

		this.activeFlag = activeFlag;
	}

	@Column(name = "standardOffer")
	public Boolean getStandardOffer() {

		return this.standardOffer;
	}

	public void setStandardOffer(Boolean standardOffer) {

		this.standardOffer = standardOffer;
	}

	@Column(name = "offerTotal", precision = 18)
	public Double getOfferTotal() {

		return this.offerTotal;
	}

	public void setOfferTotal(Double offerTotal) {

		this.offerTotal = offerTotal;
	}

	@Column(name = "salesPerson", length = 100)
	public String getSalesPerson() {

		return this.salesPerson;
	}

	public void setSalesPerson(String salesPerson) {

		this.salesPerson = salesPerson;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@Override
	public boolean equals(Object other) {

		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MisOfferId))
			return false;
		MisOfferId castOther = (MisOfferId) other;

		return (this.getOfferMasterId() == castOther.getOfferMasterId())
				&& ((this.getOfferNo() == castOther.getOfferNo())
						|| (this.getOfferNo() != null && castOther.getOfferNo() != null && this.getOfferNo().equals(castOther.getOfferNo())))
				&& (this.getOfferRevId() == castOther.getOfferRevId())
				&& ((this.getOfferRev() == castOther.getOfferRev())
						|| (this.getOfferRev() != null && castOther.getOfferRev() != null && this.getOfferRev().equals(castOther.getOfferRev())))
				&& ((this.getIsOrder() == castOther.getIsOrder())
						|| (this.getIsOrder() != null && castOther.getIsOrder() != null && this.getIsOrder().equals(castOther.getIsOrder())))
				&& ((this.getOrderPrice() == castOther.getOrderPrice()) || (this.getOrderPrice() != null && castOther.getOrderPrice() != null
						&& this.getOrderPrice().equals(castOther.getOrderPrice())))
				&& ((this.getSegmentId() == castOther.getSegmentId())
						|| (this.getSegmentId() != null && castOther.getSegmentId() != null && this.getSegmentId().equals(castOther.getSegmentId())))
				&& ((this.getSegment() == castOther.getSegment())
						|| (this.getSegment() != null && castOther.getSegment() != null && this.getSegment().equals(castOther.getSegment())))
				&& ((this.getOfferDate() == castOther.getOfferDate())
						|| (this.getOfferDate() != null && castOther.getOfferDate() != null && this.getOfferDate().equals(castOther.getOfferDate())))
				&& ((this.getCustomerId() == castOther.getCustomerId()) || (this.getCustomerId() != null && castOther.getCustomerId() != null
						&& this.getCustomerId().equals(castOther.getCustomerId())))
				&& ((this.getCustomerName() == castOther.getCustomerName()) || (this.getCustomerName() != null && castOther.getCustomerName() != null
						&& this.getCustomerName().equals(castOther.getCustomerName())))
				&& ((this.getOfferStatus() == castOther.getOfferStatus()) || (this.getOfferStatus() != null && castOther.getOfferStatus() != null
						&& this.getOfferStatus().equals(castOther.getOfferStatus())))
				&& ((this.getProject() == castOther.getProject())
						|| (this.getProject() != null && castOther.getProject() != null && this.getProject().equals(castOther.getProject())))
				&& ((this.getConsultant() == castOther.getConsultant()) || (this.getConsultant() != null && castOther.getConsultant() != null
						&& this.getConsultant().equals(castOther.getConsultant())))
				&& ((this.getEndUser() == castOther.getEndUser())
						|| (this.getEndUser() != null && castOther.getEndUser() != null && this.getEndUser().equals(castOther.getEndUser())))
				&& ((this.getContractor() == castOther.getContractor()) || (this.getContractor() != null && castOther.getContractor() != null
						&& this.getContractor().equals(castOther.getContractor())))
				&& ((this.getCurrency() == castOther.getCurrency())
						|| (this.getCurrency() != null && castOther.getCurrency() != null && this.getCurrency().equals(castOther.getCurrency())))
				&& ((this.getLoginId() == castOther.getLoginId())
						|| (this.getLoginId() != null && castOther.getLoginId() != null && this.getLoginId().equals(castOther.getLoginId())))
				&& ((this.getActiveFlag() == castOther.getActiveFlag()) || (this.getActiveFlag() != null && castOther.getActiveFlag() != null
						&& this.getActiveFlag().equals(castOther.getActiveFlag())))
				&& ((this.getStandardOffer() == castOther.getStandardOffer()) || (this.getStandardOffer() != null
						&& castOther.getStandardOffer() != null && this.getStandardOffer().equals(castOther.getStandardOffer())))
				&& ((this.getOfferTotal() == castOther.getOfferTotal()) || (this.getOfferTotal() != null && castOther.getOfferTotal() != null
						&& this.getOfferTotal().equals(castOther.getOfferTotal())))
				&& ((this.getSalesPerson() == castOther.getSalesPerson()) || (this.getSalesPerson() != null && castOther.getSalesPerson() != null
						&& this.getSalesPerson().equals(castOther.getSalesPerson())))
				&& ((this.getCompany() == castOther.getCompany())
						|| (this.getCompany() != null && castOther.getCompany() != null && this.getCompany().equals(castOther.getCompany())));
	}

	@Override
	public int hashCode() {

		int result = 17;

		result = 37 * result + this.getOfferMasterId();
		result = 37 * result + (getOfferNo() == null ? 0 : this.getOfferNo().hashCode());
		result = 37 * result + this.getOfferRevId();
		result = 37 * result + (getOfferRev() == null ? 0 : this.getOfferRev().hashCode());
		result = 37 * result + (getIsOrder() == null ? 0 : this.getIsOrder().hashCode());
		result = 37 * result + (getOrderPrice() == null ? 0 : this.getOrderPrice().hashCode());
		result = 37 * result + (getSegmentId() == null ? 0 : this.getSegmentId().hashCode());
		result = 37 * result + (getSegment() == null ? 0 : this.getSegment().hashCode());
		result = 37 * result + (getOfferDate() == null ? 0 : this.getOfferDate().hashCode());
		result = 37 * result + (getCustomerId() == null ? 0 : this.getCustomerId().hashCode());
		result = 37 * result + (getCustomerName() == null ? 0 : this.getCustomerName().hashCode());
		result = 37 * result + (getOfferStatus() == null ? 0 : this.getOfferStatus().hashCode());
		result = 37 * result + (getProject() == null ? 0 : this.getProject().hashCode());
		result = 37 * result + (getConsultant() == null ? 0 : this.getConsultant().hashCode());
		result = 37 * result + (getEndUser() == null ? 0 : this.getEndUser().hashCode());
		result = 37 * result + (getContractor() == null ? 0 : this.getContractor().hashCode());
		result = 37 * result + (getCurrency() == null ? 0 : this.getCurrency().hashCode());
		result = 37 * result + (getLoginId() == null ? 0 : this.getLoginId().hashCode());
		result = 37 * result + (getActiveFlag() == null ? 0 : this.getActiveFlag().hashCode());
		result = 37 * result + (getStandardOffer() == null ? 0 : this.getStandardOffer().hashCode());
		result = 37 * result + (getOfferTotal() == null ? 0 : this.getOfferTotal().hashCode());
		result = 37 * result + (getSalesPerson() == null ? 0 : this.getSalesPerson().hashCode());
		result = 37 * result + (getCompany() == null ? 0 : this.getCompany().hashCode());
		return result;
	}

}
