
package com.velotech.fanselection.models;
// Generated May 29, 2019 3:23:32 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.ParamDef;
import org.hibernate.annotations.Parameter;

/**
 * Tbl27RequirementsDp generated by hbm2java
 */
@Entity
@Table(name = "tbl_27_requirementsDP")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl27RequirementsDp implements java.io.Serializable {

	private int id;

	private Tbl26OfferFan tbl26OfferFan;
	
	//private String fanModel;

	private Double flow;

	private Double head;

	private Double flowConverted;

	private Double headConverted;

	private String system;

	private String pumpQtyinSystem;

	private Integer qty;


	private String uomFlow;

	private String uomHead;

	private String uomPower;

	private String uomPressure;

	private String solidSize;

	private String solidConcentration;

	private String uomSolidSize;

	private Double spgr;

	private String series;

	private String verticalLogic;

	private String minSoh;

	private String maxSoh;

	private String maxFlow;

	private String minHead;

	private String addEff;

	private Boolean effModImpeller;

	private Boolean effModMoc;

	private Boolean effModStages;

	private Boolean effModCoating;

	private String frequency;

	private String type;

	private String manufacturer;

	private String ambientTemp;

	private String tempRiseClass;

	private String pole;

	private String effclass;

	private String searchCriteria;

	private Integer speed;

	private String driverSizing;

	private Double serviceFactor;

	private String mounting;

	private String specification;

	private Boolean closedCoupled;

	private String typeOfDrive;

	private String testingStd;

	private String seal;

	private String lubrication;

	private String application;

	private String constant;

	private Integer flowMissToleranceMin;

	private Integer headMissToleranceMin;

	private String selectionRange;

	private String dp_searchCriteria;

	private Integer dp_speed;

	private Integer phase;

	private Integer selectionTypeId;

	private Double dp_temperature;

	private Integer borewellSize;

	private Integer equivalentMotorSeriesId;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl27RequirementsDp() {
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "tbl26OfferFan"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Tbl26OfferFan getTbl26OfferFan() {

		return this.tbl26OfferFan;
	}

	public void setTbl26OfferFan(Tbl26OfferFan tbl26OfferFan) {

		this.tbl26OfferFan = tbl26OfferFan;
	}
	
	
	
	/*
	 * @Column(name = "fanModel", length = 50) public String getFanModel() { return
	 * fanModel; }
	 * 
	 * public void setFanModel(String fanModel) { this.fanModel = fanModel; }
	 */

	@Column(name = "flow", precision = 18)
	public Double getFlow() {

		return this.flow;
	}

	public void setFlow(Double flow) {

		this.flow = flow;
	}

	@Column(name = "head", precision = 18)
	public Double getHead() {

		return this.head;
	}

	public void setHead(Double head) {

		this.head = head;
	}

	@Column(name = "flowConverted", precision = 18)
	public Double getFlowConverted() {

		return this.flowConverted;
	}

	public void setFlowConverted(Double flowConverted) {

		this.flowConverted = flowConverted;
	}

	@Column(name = "headConverted", precision = 18)
	public Double getHeadConverted() {

		return this.headConverted;
	}

	public void setHeadConverted(Double headConverted) {

		this.headConverted = headConverted;
	}

	@Column(name = "system", length = 50)
	public String getSystem() {

		return this.system;
	}

	public void setSystem(String system) {

		this.system = system;
	}

	@Column(name = "pumpQtyinSystem", length = 50)
	public String getPumpQtyinSystem() {

		return this.pumpQtyinSystem;
	}

	public void setPumpQtyinSystem(String pumpQtyinSystem) {

		this.pumpQtyinSystem = pumpQtyinSystem;
	}

	@Column(name = "qty")
	public Integer getQty() {

		return this.qty;
	}

	public void setQty(Integer qty) {

		this.qty = qty;
	}

	

	@Column(name = "uomFlow", length = 50)
	public String getUomFlow() {

		return this.uomFlow;
	}

	public void setUomFlow(String uomFlow) {

		this.uomFlow = uomFlow;
	}

	@Column(name = "uomHead", length = 50)
	public String getUomHead() {

		return this.uomHead;
	}

	public void setUomHead(String uomHead) {

		this.uomHead = uomHead;
	}

	@Column(name = "uomPower", length = 50)
	public String getUomPower() {

		return uomPower;
	}

	public void setUomPower(String uomPower) {

		this.uomPower = uomPower;
	}


	@Column(name = "uomPressure", length = 50)
	public String getUomPressure() {

		return this.uomPressure;
	}

	public void setUomPressure(String uomPressure) {

		this.uomPressure = uomPressure;
	}

	@Column(name = "solidSize", length = 50)
	public String getSolidSize() {

		return this.solidSize;
	}

	public void setSolidSize(String solidSize) {

		this.solidSize = solidSize;
	}

	@Column(name = "solidConcentration", length = 50)
	public String getSolidConcentration() {

		return this.solidConcentration;
	}

	public void setSolidConcentration(String solidConcentration) {

		this.solidConcentration = solidConcentration;
	}

	@Column(name = "uomSolidSize", length = 50)
	public String getUomSolidSize() {

		return this.uomSolidSize;
	}

	public void setUomSolidSize(String uomSolidSize) {

		this.uomSolidSize = uomSolidSize;
	}

	@Column(name = "spgr", precision = 18)
	public Double getSpgr() {

		return this.spgr;
	}

	public void setSpgr(Double spgr) {

		this.spgr = spgr;
	}

	@Column(name = "series", length = 50)
	public String getSeries() {

		return this.series;
	}

	public void setSeries(String series) {

		this.series = series;
	}

	@Column(name = "verticalLogic", length = 50)
	public String getVerticalLogic() {

		return this.verticalLogic;
	}

	public void setVerticalLogic(String verticalLogic) {

		this.verticalLogic = verticalLogic;
	}

	@Column(name = "minSOH", length = 50)
	public String getMinSoh() {

		return this.minSoh;
	}

	public void setMinSoh(String minSoh) {

		this.minSoh = minSoh;
	}

	@Column(name = "maxSOH", length = 50)
	public String getMaxSoh() {

		return this.maxSoh;
	}

	public void setMaxSoh(String maxSoh) {

		this.maxSoh = maxSoh;
	}

	@Column(name = "maxFlow", length = 50)
	public String getMaxFlow() {

		return this.maxFlow;
	}

	public void setMaxFlow(String maxFlow) {

		this.maxFlow = maxFlow;
	}

	@Column(name = "minHead", length = 50)
	public String getMinHead() {

		return this.minHead;
	}

	public void setMinHead(String minHead) {

		this.minHead = minHead;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@Column(name = "addEff", length = 50)
	public String getAddEff() {

		return this.addEff;
	}

	public void setAddEff(String addEff) {

		this.addEff = addEff;
	}

	@Column(name = "effMod_impeller")
	public Boolean getEffModImpeller() {

		return this.effModImpeller;
	}

	public void setEffModImpeller(Boolean effModImpeller) {

		this.effModImpeller = effModImpeller;
	}

	@Column(name = "effMod_MOC")
	public Boolean getEffModMoc() {

		return this.effModMoc;
	}

	public void setEffModMoc(Boolean effModMoc) {

		this.effModMoc = effModMoc;
	}

	@Column(name = "effMod_stages")
	public Boolean getEffModStages() {

		return this.effModStages;
	}

	public void setEffModStages(Boolean effModStages) {

		this.effModStages = effModStages;
	}

	@Column(name = "effMod_coating")
	public Boolean getEffModCoating() {

		return this.effModCoating;
	}

	public void setEffModCoating(Boolean effModCoating) {

		this.effModCoating = effModCoating;
	}

	@Column(name = "frequency", length = 50)
	public String getFrequency() {

		return this.frequency;
	}

	public void setFrequency(String frequency) {

		this.frequency = frequency;
	}

	@Column(name = "type", length = 50)
	public String getType() {

		return this.type;
	}

	public void setType(String type) {

		this.type = type;
	}

	@Column(name = "manufacturer", length = 50)
	public String getManufacturer() {

		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {

		this.manufacturer = manufacturer;
	}

	@Column(name = "ambientTemp", length = 50)
	public String getAmbientTemp() {

		return this.ambientTemp;
	}

	public void setAmbientTemp(String ambientTemp) {

		this.ambientTemp = ambientTemp;
	}

	@Column(name = "tempRiseClass", length = 50)
	public String getTempRiseClass() {

		return this.tempRiseClass;
	}

	public void setTempRiseClass(String tempRiseClass) {

		this.tempRiseClass = tempRiseClass;
	}

	@Column(name = "pole", length = 50)
	public String getPole() {

		return this.pole;
	}

	public void setPole(String pole) {

		this.pole = pole;
	}

	@Column(name = "effclass", length = 50)
	public String getEffclass() {

		return this.effclass;
	}

	public void setEffclass(String effclass) {

		this.effclass = effclass;
	}

	@Column(name = "searchCriteria", length = 50)
	public String getSearchCriteria() {

		return this.searchCriteria;
	}

	public void setSearchCriteria(String searchCriteria) {

		this.searchCriteria = searchCriteria;
	}

	@Column(name = "speed", length = 50)
	public Integer getSpeed() {

		return this.speed;
	}

	public void setSpeed(Integer speed) {

		this.speed = speed;
	}

	@Column(name = "driverSizing", length = 50)
	public String getDriverSizing() {

		return this.driverSizing;
	}

	public void setDriverSizing(String driverSizing) {

		this.driverSizing = driverSizing;
	}

	@Column(name = "serviceFactor", length = 50)
	public Double getServiceFactor() {

		return this.serviceFactor;
	}

	public void setServiceFactor(Double serviceFactor) {

		this.serviceFactor = serviceFactor;
	}

	@Column(name = "mounting", length = 50)
	public String getMounting() {

		return this.mounting;
	}

	public void setMounting(String mounting) {

		this.mounting = mounting;
	}

	@Column(name = "specification", length = 50)
	public String getSpecification() {

		return this.specification;
	}

	public void setSpecification(String specification) {

		this.specification = specification;
	}

	@Column(name = "closedCoupled")
	public Boolean getClosedCoupled() {

		return this.closedCoupled;
	}

	public void setClosedCoupled(Boolean closedCoupled) {

		this.closedCoupled = closedCoupled;
	}

	@Column(name = "typeOfDrive")
	public String getTypeOfDrive() {

		return this.typeOfDrive;
	}

	public void setTypeOfDrive(String typeOfDrive) {

		this.typeOfDrive = typeOfDrive;
	}

	@Column(name = "testingStd", length = 50)
	public String getTestingStd() {

		return this.testingStd;
	}

	public void setTestingStd(String testingStd) {

		this.testingStd = testingStd;
	}

	@Column(name = "seal", length = 50)
	public String getSeal() {

		return this.seal;
	}

	public void setSeal(String seal) {

		this.seal = seal;
	}

	@Column(name = "lubrication", length = 50)
	public String getLubrication() {

		return this.lubrication;
	}

	public void setLubrication(String lubrication) {

		this.lubrication = lubrication;
	}

	@Column(name = "application", length = 50)
	public String getApplication() {

		return this.application;
	}

	public void setApplication(String application) {

		this.application = application;
	}

	@Column(name = "constant", length = 50)
	public String getConstant() {

		return constant;
	}

	public void setConstant(String constant) {

		this.constant = constant;
	}

	@Column(name = "flowMissToleranceMin", precision = 18)
	public Integer getFlowMissToleranceMin() {

		return flowMissToleranceMin;
	}

	public void setFlowMissToleranceMin(Integer flowMissToleranceMin) {

		this.flowMissToleranceMin = flowMissToleranceMin;
	}

	@Column(name = "headMissToleranceMin", precision = 18)
	public Integer getHeadMissToleranceMin() {

		return headMissToleranceMin;
	}

	public void setHeadMissToleranceMin(Integer headMissToleranceMin) {

		this.headMissToleranceMin = headMissToleranceMin;
	}

	@Column(name = "selectionRange", length = 50)
	public String getSelectionRange() {

		return selectionRange;
	}

	public void setSelectionRange(String selectionRange) {

		this.selectionRange = selectionRange;
	}

	@Column(name = "dp_searchCriteria", length = 50)
	public String getDp_searchCriteria() {

		return dp_searchCriteria;
	}

	public void setDp_searchCriteria(String dp_searchCriteria) {

		this.dp_searchCriteria = dp_searchCriteria;
	}

	@Column(name = "dp_speed", precision = 18)
	public Integer getDp_speed() {

		return dp_speed;
	}

	public void setDp_speed(Integer dp_speed) {

		this.dp_speed = dp_speed;
	}

	@Column(name = "phase")
	public Integer getPhase() {

		return phase;
	}

	public void setPhase(Integer phase) {

		this.phase = phase;
	}

	@Column(name = "selectionTypeId")
	public Integer getSelectionTypeId() {

		return selectionTypeId;
	}

	public void setSelectionTypeId(Integer selectionTypeId) {

		this.selectionTypeId = selectionTypeId;
	}

	@Column(name = "dp_temperature", precision = 18)
	public Double getDp_temperature() {

		return dp_temperature;
	}

	public void setDp_temperature(Double dp_temperature) {

		this.dp_temperature = dp_temperature;
	}

	@Column(name = "borewellSize")
	public Integer getBorewellSize() {

		return borewellSize;
	}

	public void setBorewellSize(Integer borewellSize) {

		this.borewellSize = borewellSize;
	}

	@Column(name = "equivalentMotorSeriesId")
	public Integer getEquivalentMotorSeriesId() {

		return equivalentMotorSeriesId;
	}

	public void setEquivalentMotorSeriesId(Integer equivalentMotorSeriesId) {

		this.equivalentMotorSeriesId = equivalentMotorSeriesId;
	}

}
