
package com.velotech.fanselection.models;
// Generated 9 Nov, 2019 2:41:01 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl01ProductTypeMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_01_product_type_master")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl01ProductTypeMaster implements java.io.Serializable {

	private int id;

	private String productTypeDescription;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	private Set<Tbl01ProductMaster> tbl01ProductMasters = new HashSet<Tbl01ProductMaster>(0);

	public Tbl01ProductTypeMaster() {
	}

	public Tbl01ProductTypeMaster(int id) {
		this.id = id;
	}

	public Tbl01ProductTypeMaster(int id, String productTypeDescription, String createdBy, Date createdDate, String modifiedBy, Date modifiedDate,
			String company, Set<Tbl01ProductMaster> tbl01ProductMasters) {
		this.id = id;
		this.productTypeDescription = productTypeDescription;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.company = company;
		this.tbl01ProductMasters = tbl01ProductMasters;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@Column(name = "productTypeDescription")
	public String getProductTypeDescription() {

		return this.productTypeDescription;
	}

	public void setProductTypeDescription(String productTypeDescription) {

		this.productTypeDescription = productTypeDescription;
	}
	
	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbl01ProductTypeMaster")
	public Set<Tbl01ProductMaster> getTbl01ProductMasters() {

		return this.tbl01ProductMasters;
	}

	public void setTbl01ProductMasters(Set<Tbl01ProductMaster> tbl01ProductMasters) {

		this.tbl01ProductMasters = tbl01ProductMasters;
	}

}
