
package com.velotech.fanselection.models;
// Generated May 29, 2019 3:23:32 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl28SelectedpricingDetails generated by hbm2java
 */
@Entity
@Table(name = "tbl_28_selectedpricing_details")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl28SelectedpricingDetails implements java.io.Serializable {

	private int id;

	private Tbl28SelectedPricing tbl28SelectedPricing;

	private String parameter;

	private String value;

	private Boolean showInSummary;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl28SelectedpricingDetails() {
	}

	public Tbl28SelectedpricingDetails(int id) {
		this.id = id;
	}

	public Tbl28SelectedpricingDetails(String parameter, String value, Boolean showInSummary) {
		this.parameter = parameter;
		this.value = value;
		this.showInSummary = showInSummary;
	}

	public Tbl28SelectedpricingDetails(String parameter, String value, Tbl28SelectedPricing tbl28SelectedPricing, Boolean showInSummary) {
		this.parameter = parameter;
		this.value = value;
		this.tbl28SelectedPricing = tbl28SelectedPricing;
		this.showInSummary = showInSummary;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "selectedPricingId")
	public Tbl28SelectedPricing getTbl28SelectedPricing() {

		return this.tbl28SelectedPricing;
	}

	public void setTbl28SelectedPricing(Tbl28SelectedPricing tbl28SelectedPricing) {

		this.tbl28SelectedPricing = tbl28SelectedPricing;
	}

	@Column(name = "parameter")
	public String getParameter() {

		return this.parameter;
	}

	public void setParameter(String parameter) {

		this.parameter = parameter;
	}

	@Column(name = "value")
	public String getValue() {

		return this.value;
	}

	public void setValue(String value) {

		this.value = value;
	}

	@Column(name = "showInSummary")
	public Boolean getShowInSummary() {

		return this.showInSummary;
	}

	public void setShowInSummary(Boolean showInSummary) {

		this.showInSummary = showInSummary;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

}
