
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

import com.google.gson.annotations.Expose;

/**
 * Tbl28CompanyMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_28_companyMaster", uniqueConstraints = @UniqueConstraint(columnNames = {
		"companyName", "company" }))
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl28CompanyMaster implements java.io.Serializable {

	private int id;
	@Expose
	private String companyName;
	@Expose
	private String logo;
	@Expose
	private String address;
	@Expose
	private String email;

	private String currency;

	private String country;

	private String contactPhone;

	private String city;

	private String website;

	private String tinNo;

	private String state;

	private String postalCode;

	private String panNo;

	private String mobileNo;
	@Expose
	private String documentCompanyName;
	@Expose
	private String documentComapnyAddress;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;
	@Expose
	private String gstNo;

	public Tbl28CompanyMaster() {
	}

	public Tbl28CompanyMaster(int id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@Column(name = "companyName", nullable = false)
	public String getCompanyName() {

		return this.companyName;
	}

	public void setCompanyName(String companyName) {

		this.companyName = companyName;
	}

	@Column(name = "logo", length = 50)
	public String getLogo() {

		return this.logo;
	}

	public void setLogo(String logo) {

		this.logo = logo;
	}

	@Column(name = "address", columnDefinition = "TEXT")
	public String getAddress() {

		return this.address;
	}

	public void setAddress(String address) {

		this.address = address;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {

		return this.email;
	}

	public void setEmail(String email) {

		this.email = email;
	}

	@Column(name = "currency", length = 50)
	public String getCurrency() {

		return this.currency;
	}

	public void setCurrency(String currency) {

		this.currency = currency;
	}

	@Column(name = "country", length = 50)
	public String getCountry() {

		return this.country;
	}

	public void setCountry(String country) {

		this.country = country;
	}

	@Column(name = "contactPhone", length = 50)
	public String getContactPhone() {

		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {

		this.contactPhone = contactPhone;
	}

	@Column(name = "city", length = 50)
	public String getCity() {

		return this.city;
	}

	public void setCity(String city) {

		this.city = city;
	}

	@Column(name = "website", length = 100)
	public String getWebsite() {

		return this.website;
	}

	public void setWebsite(String website) {

		this.website = website;
	}

	@Column(name = "tinNo", length = 50)
	public String getTinNo() {

		return this.tinNo;
	}

	public void setTinNo(String tinNo) {

		this.tinNo = tinNo;
	}

	@Column(name = "state", length = 50)
	public String getState() {

		return this.state;
	}

	public void setState(String state) {

		this.state = state;
	}

	@Column(name = "postalCode", length = 10)
	public String getPostalCode() {

		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {

		this.postalCode = postalCode;
	}

	@Column(name = "panNo", length = 50)
	public String getPanNo() {

		return this.panNo;
	}

	public void setPanNo(String panNo) {

		this.panNo = panNo;
	}

	@Column(name = "mobileNo", length = 50)
	public String getMobileNo() {

		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {

		this.mobileNo = mobileNo;
	}

	@Column(name = "documentCompanyName", columnDefinition = "TEXT")
	public String getDocumentCompanyName() {

		return this.documentCompanyName;
	}

	public void setDocumentCompanyName(String documentCompanyName) {

		this.documentCompanyName = documentCompanyName;
	}

	@Column(name = "documentComapnyAddress", columnDefinition = "TEXT")
	public String getDocumentComapnyAddress() {

		return this.documentComapnyAddress;
	}

	public void setDocumentComapnyAddress(String documentComapnyAddress) {

		this.documentComapnyAddress = documentComapnyAddress;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@Column(name = "gstNo", length = 200)
	public String getGstNo() {

		return this.gstNo;
	}

	public void setGstNo(String gstNo) {

		this.gstNo = gstNo;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

}
