
package com.velotech.fanselection.models;
// Generated 5 Dec, 2022 12:18:41 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl90JsonMaster generated by hbm2java
 */
@Entity
@Table(name = "tbl_90_jsonMaster", uniqueConstraints = @UniqueConstraint(columnNames = { "jsonName", "company" }))
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl90JsonMaster implements java.io.Serializable {

	private int id;

	private Tbl90ParameterMaster tbl90ParameterMaster;

	private String jsonText;

	private String uuid;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl90JsonMaster() {
	}

	public Tbl90JsonMaster(int id) {
		this.id = id;
	}

	public Tbl90JsonMaster(int id, Tbl90ParameterMaster tbl90ParameterMaster, String jsonText, String createdBy, Date createdDate,
			String modifiedBy, Date modifiedDate, String company) {
		this.id = id;
		this.tbl90ParameterMaster = tbl90ParameterMaster;
		this.jsonText = jsonText;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.company = company;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jsonName",unique = true)
	public Tbl90ParameterMaster getTbl90ParameterMaster() {
		return tbl90ParameterMaster;
	}

	public void setTbl90ParameterMaster(Tbl90ParameterMaster tbl90ParameterMaster) {
		this.tbl90ParameterMaster = tbl90ParameterMaster;
	}

	@Column(name = "jsonText"/* , columnDefinition = "TEXT" */)
	public String getJsonText() {

		return this.jsonText;
	}
	
	public void setJsonText(String jsonText) {

		this.jsonText = jsonText;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

	@Column(name = "uuid")
	public String getUuid() {

		return uuid;
	}

	public void setUuid(String uuid) {

		this.uuid = uuid;
	}

	@Override
	public String toString() {
		return "Tbl90JsonMaster [id=" + id + ", tbl90ParameterMaster=" + tbl90ParameterMaster + ", jsonText=" + jsonText
				+ ", uuid=" + uuid + ", createdBy=" + createdBy + ", createdDate=" + createdDate + ", modifiedBy="
				+ modifiedBy + ", modifiedDate=" + modifiedDate + ", company=" + company + "]";
	}
	

}
