
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;

/**
 * Tbl02ModelPrice generated by hbm2java
 */
@Entity
@Table(name = "tbl_02_model_price")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl02ModelPrice implements java.io.Serializable {

	private int id;

	private Tbl01VariantMaster tbl01VariantMaster;
	
	private Tbl01CentrifugalModelMaster tbl01CentrifugalModelMaster;

	private Tbl14PrimemoverMaster tbl14PrimemoverMaster;

	private String description;

	private String mocStd;

	private String articleNo;

	private BigDecimal price;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl02ModelPrice() {

	}

	public Tbl02ModelPrice(int id) {

		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "variantId")
	public Tbl01VariantMaster getTbl01VariantMaster() {

		return this.tbl01VariantMaster;
	}

	public void setTbl01VariantMaster(Tbl01VariantMaster tbl01VariantMaster) {

		this.tbl01VariantMaster = tbl01VariantMaster;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "centrifugalModelId")
	public Tbl01CentrifugalModelMaster getTbl01CentrifugalModelMaster() {
		return tbl01CentrifugalModelMaster;
	}

	public void setTbl01CentrifugalModelMaster(Tbl01CentrifugalModelMaster tbl01CentrifugalModelMaster) {
		this.tbl01CentrifugalModelMaster = tbl01CentrifugalModelMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "primemover_id")
	public Tbl14PrimemoverMaster getTbl14PrimemoverMaster() {

		return this.tbl14PrimemoverMaster;
	}

	public void setTbl14PrimemoverMaster(Tbl14PrimemoverMaster tbl14PrimemoverMaster) {

		this.tbl14PrimemoverMaster = tbl14PrimemoverMaster;
	}

	@Column(name = "description", length = 255)
	public String getDescription() {

		return description;
	}

	public void setDescription(String description) {

		this.description = description;
	}


	@Column(name = "mocStd", length = 50)
	public String getMocStd() {

		return this.mocStd;
	}

	public void setMocStd(String mocStd) {

		this.mocStd = mocStd;
	}


	@Column(name = "articleNo", length = 50)
	public String getArticleNo() {

		return this.articleNo;
	}

	public void setArticleNo(String articleNo) {

		this.articleNo = articleNo;
	}

	@Column(name = "price", precision = 18)
	public BigDecimal getPrice() {

		return this.price;
	}

	public void setPrice(BigDecimal price) {

		this.price = price;
	}


	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

}
