
package com.velotech.fanselection.models;
// Generated May 2, 2019 12:45:56 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;
/**
 * Tbl27OfferPumpDp generated by hbm2java
 */
@Entity
@Table(name = "tbl_27_offerFan_dp")
@FilterDef(name = "company", parameters = { @ParamDef(name = "company", type = "java.lang.String") })
@Filter(name = "company", condition = ":company= company ")
public class Tbl27OfferFanDp implements java.io.Serializable {

	private int offerFanDpId;

	private Tbl26OfferFan tbl26OfferFan;

	private String flow;

	private String head;

	private String speed;

	private String createdBy;

	private Date createdDate;

	private String modifiedBy;

	private Date modifiedDate;

	private String company;

	public Tbl27OfferFanDp() {
	}

	public Tbl27OfferFanDp(Tbl26OfferFan tbl26OfferFan) {
		this.tbl26OfferFan = tbl26OfferFan;
	}

	public Tbl27OfferFanDp(Tbl26OfferFan tbl26OfferFan, String flow, String head, String speed) {
		this.tbl26OfferFan = tbl26OfferFan;
		this.flow = flow;
		this.head = head;
		this.speed = speed;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "tbl26OfferFan"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "offerFanDP_id", unique = true, nullable = false)
	public int getOfferFanDpId() {

		return this.offerFanDpId;
	}

	public void setOfferFanDpId(int offerFanDpId) {

		this.offerFanDpId = offerFanDpId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Tbl26OfferFan getTbl26OfferFan() {

		return this.tbl26OfferFan;
	}

	public void setTbl26OfferFan(Tbl26OfferFan tbl26OfferFan) {

		this.tbl26OfferFan = tbl26OfferFan;
	}

	@Column(name = "flow", columnDefinition = "TEXT")
	public String getFlow() {

		return this.flow;
	}

	public void setFlow(String flow) {

		this.flow = flow;
	}

	@Column(name = "head", columnDefinition = "TEXT")
	public String getHead() {

		return this.head;
	}

	public void setHead(String head) {

		this.head = head;
	}

	@Column(name = "speed", columnDefinition = "TEXT")
	public String getSpeed() {

		return this.speed;
	}

	public void setSpeed(String speed) {

		this.speed = speed;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {

		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {

		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {

		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {

		this.createdDate = createdDate;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {

		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifiedDate", length = 10)
	public Date getModifiedDate() {

		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {

		return this.company;
	}

	public void setCompany(String company) {

		this.company = company;
	}

}
